/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/consumption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log a consumption via audio
         * @description Upload an audio file of spoken consumption data to be transcribed, parsed, and analyzed for nutrition information
         */
        post: operations["createConsumption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Get the health status of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List consumptions (development only)
         * @description Get a list of stored consumptions for the default user
         */
        get: operations["getConsumptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get nutrition summary (development only)
         * @description Get aggregated nutrition data over a time period
         */
        get: operations["getNutritionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Error message */
            error: string;
            /** @description HTTP status code */
            code: number;
            /**
             * Format: date-time
             * @description Timestamp when the error occurred
             */
            timestamp: string;
            /** @description Stack trace (only in debug mode) */
            stack?: string[];
            /** @description Request trace ID */
            trace_id?: string;
        };
        HealthResponse: {
            /** @example healthy */
            status: string;
            /** Format: date-time */
            timestamp: string;
            /** @example dev */
            version: string;
        };
        ConsumptionResponse: {
            /** @description Transcribed text from audio */
            transcript: string;
            /** @description Items parsed from transcript (without nutrition data) */
            parsedItems: components["schemas"]["Item"][];
            /** @description Items with complete nutrition information */
            items: components["schemas"]["ItemWithNutrition"][];
            summary: components["schemas"]["Summary"];
            /** @description Request identifier for tracking */
            request_id: string;
        };
        ConsumptionsResponse: {
            consumptions: components["schemas"]["Consumption"][];
            user: components["schemas"]["User"];
            /** @description Number of consumptions returned */
            count: number;
        };
        NutritionSummaryResponse: {
            summary: components["schemas"]["NutritionSummary"];
            user: components["schemas"]["User"];
            /** @description Number of days in the summary */
            days: number;
            date_range: {
                /** Format: date-time */
                start?: string;
                /** Format: date-time */
                end?: string;
            };
        };
        Item: {
            /** @description Name of the food item */
            name: string;
            /** @description Quantity consumed */
            quantity?: number | null;
            /** @description Unit of measurement */
            unit?: string | null;
            /** @description Brand name */
            brand?: string | null;
            nutrients?: components["schemas"]["CompleteNutrient"];
        };
        ItemWithNutrition: {
            item: components["schemas"]["Item"];
            /** @description Additional note (e.g., if nutrition data unavailable) */
            note?: string;
        };
        CompleteNutrient: {
            /** @description Calories per serving */
            calories: number;
            /** @description Protein in grams */
            protein_g: number;
            /** @description Total fat in grams */
            total_fat_g: number;
            /** @description Saturated fat in grams */
            saturated_fat_g: number;
            /** @description Trans fat in grams */
            trans_fat_g: number;
            /** @description Cholesterol in milligrams */
            cholesterol_mg: number;
            /** @description Sodium in milligrams */
            sodium_mg: number;
            /** @description Total carbohydrates in grams */
            total_carbs_g: number;
            /** @description Dietary fiber in grams */
            dietary_fiber_g: number;
            /** @description Total sugars in grams */
            total_sugars_g: number;
            /** @description Added sugars in grams */
            added_sugars_g: number;
            /** @description Vitamin A in micrograms */
            vitamin_a_mcg: number;
            /** @description Vitamin C in milligrams */
            vitamin_c_mg: number;
            /** @description Vitamin D in micrograms */
            vitamin_d_mcg: number;
            /** @description Vitamin E in milligrams */
            vitamin_e_mg: number;
            /** @description Vitamin K in micrograms */
            vitamin_k_mcg: number;
            /** @description Thiamine (B1) in milligrams */
            thiamine_mg: number;
            /** @description Riboflavin (B2) in milligrams */
            riboflavin_mg: number;
            /** @description Niacin (B3) in milligrams */
            niacin_mg: number;
            /** @description Vitamin B6 in milligrams */
            vitamin_b6_mg: number;
            /** @description Folate in micrograms */
            folate_mcg: number;
            /** @description Vitamin B12 in micrograms */
            vitamin_b12_mcg: number;
            /** @description Calcium in milligrams */
            calcium_mg: number;
            /** @description Iron in milligrams */
            iron_mg: number;
            /** @description Magnesium in milligrams */
            magnesium_mg: number;
            /** @description Phosphorus in milligrams */
            phosphorus_mg: number;
            /** @description Potassium in milligrams */
            potassium_mg: number;
            /** @description Zinc in milligrams */
            zinc_mg: number;
            /** @description Copper in milligrams */
            copper_mg: number;
            /** @description Manganese in milligrams */
            manganese_mg: number;
            /** @description Selenium in micrograms */
            selenium_mcg: number;
        };
        Summary: {
            totals: components["schemas"]["CompleteNutrient"];
            /** @description Percentage of daily values for each nutrient */
            percent_of_daily: {
                [key: string]: number;
            };
            /** @description Daily value amounts used for calculations */
            daily_values: {
                [key: string]: number;
            };
        };
        User: {
            /** @description User ID */
            id: string;
            /** @description Authentication provider */
            provider: string;
            /** @description Provider-specific user identifier */
            subject: string;
            /** @description User email address */
            email: string;
            /**
             * @description User subscription level
             * @enum {string}
             */
            subscription_tier: "free" | "pro";
            /**
             * Format: date-time
             * @description User creation timestamp
             */
            created_at: string;
        };
        Consumption: {
            /** @description Consumption ID */
            id: string;
            /** @description User ID who logged this consumption */
            user_id: string;
            /** @description Original transcribed text */
            transcript: string;
            items: components["schemas"]["ItemWithNutrition"][];
            summary: components["schemas"]["Summary"];
            /**
             * Format: date-time
             * @description Timestamp when consumption was logged
             */
            created_at: string;
        };
        NutritionSummary: {
            /** @description User ID */
            user_id: string;
            /**
             * Format: date-time
             * @description Start date of the summary period
             */
            start_date: string;
            /**
             * Format: date-time
             * @description End date of the summary period
             */
            end_date: string;
            /** @description Total number of consumptions in the period */
            consumption_count: number;
            /** @description Total calories consumed */
            total_calories: number;
            /** @description Total protein in grams */
            total_protein_g: number;
            /** @description Total fat in grams */
            total_fat_g: number;
            /** @description Total carbohydrates in grams */
            total_carbs_g: number;
            /** @description Total fiber in grams */
            total_fiber_g: number;
            /** @description Total sodium in milligrams */
            total_sodium_mg: number;
            /** @description Average calories per day */
            avg_calories_per_day: number;
            /** @description Average protein per day in grams */
            avg_protein_per_day: number;
            /** @description Average fat per day in grams */
            avg_fat_per_day: number;
            /** @description Average carbs per day in grams */
            avg_carbs_per_day: number;
            /** @description Average fiber per day in grams */
            avg_fiber_per_day: number;
            /** @description Average sodium per day in milligrams */
            avg_sodium_per_day: number;
            /** @description Daily nutrition breakdown */
            daily_breakdown: components["schemas"]["DailySummary"][];
        };
        DailySummary: {
            /**
             * Format: date-time
             * @description Date for this daily summary
             */
            date: string;
            /** @description Number of consumptions on this date */
            consumption_count: number;
            /** @description Total calories for the day */
            calories: number;
            /** @description Total protein in grams for the day */
            protein_g: number;
            /** @description Total fat in grams for the day */
            total_fat_g: number;
            /** @description Total carbohydrates in grams for the day */
            total_carbs_g: number;
            /** @description Total fiber in grams for the day */
            fiber_g: number;
            /** @description Total sodium in milligrams for the day */
            sodium_mg: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createConsumption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Audio file (webm, opus, mp3, wav)
                     */
                    audio: string;
                };
            };
        };
        responses: {
            /** @description Successful consumption analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumptionResponse"];
                };
            };
            /** @description Bad request (invalid multipart form, no audio file, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getConsumptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of consumptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumptionsResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getNutritionSummary: {
        parameters: {
            query?: {
                /** @description Start date (RFC3339 format) */
                start?: string;
                /** @description End date (RFC3339 format) */
                end?: string;
                /** @description Number of days to look back from today */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nutrition summary data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionSummaryResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied (subscription limitation) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
