// Nutrient field mappings for query builder
// THIS FILE IS GENERATED - DO NOT EDIT MANUALLY
// Generated from nutrients.yaml

package storage

// GetNutrientFields returns all nutrition-related database columns and their corresponding struct field names
func GetNutrientFields() []NutrientField {
	per100gFields := []NutrientField{
		{"calories_per_100g", "CaloriesPer100g"},
		{"protein_g_per_100g", "ProteinGPer100g"},
		{"total_fat_g_per_100g", "TotalFatGPer100g"},
		{"saturated_fat_g_per_100g", "SaturatedFatGPer100g"},
		{"trans_fat_g_per_100g", "TransFatGPer100g"},
		{"monounsaturated_fat_g_per_100g", "MonounsaturatedFatGPer100g"},
		{"polyunsaturated_fat_g_per_100g", "PolyunsaturatedFatGPer100g"},
		{"cholesterol_mg_per_100g", "CholesterolMgPer100g"},
		{"sodium_mg_per_100g", "SodiumMgPer100g"},
		{"total_carbs_g_per_100g", "TotalCarbsGPer100g"},
		{"dietary_fiber_g_per_100g", "DietaryFiberGPer100g"},
		{"total_sugars_g_per_100g", "TotalSugarsGPer100g"},
		{"added_sugars_g_per_100g", "AddedSugarsGPer100g"},
		{"vitamin_a_mcg_per_100g", "VitaminAMcgPer100g"},
		{"vitamin_c_mg_per_100g", "VitaminCMgPer100g"},
		{"vitamin_d_mcg_per_100g", "VitaminDMcgPer100g"},
		{"vitamin_e_mg_per_100g", "VitaminEMgPer100g"},
		{"vitamin_k_mcg_per_100g", "VitaminKMcgPer100g"},
		{"thiamine_mg_per_100g", "ThiamineMgPer100g"},
		{"riboflavin_mg_per_100g", "RiboflavinMgPer100g"},
		{"niacin_mg_per_100g", "NiacinMgPer100g"},
		{"vitamin_b6_mg_per_100g", "VitaminB6MgPer100g"},
		{"folate_mcg_per_100g", "FolateMcgPer100g"},
		{"vitamin_b12_mcg_per_100g", "VitaminB12McgPer100g"},
		{"biotin_mcg_per_100g", "BiotinMcgPer100g"},
		{"pantothenic_acid_mg_per_100g", "PantothenicAcidMgPer100g"},
		{"choline_mg_per_100g", "CholineMgPer100g"},
		{"calcium_mg_per_100g", "CalciumMgPer100g"},
		{"iron_mg_per_100g", "IronMgPer100g"},
		{"magnesium_mg_per_100g", "MagnesiumMgPer100g"},
		{"phosphorus_mg_per_100g", "PhosphorusMgPer100g"},
		{"potassium_mg_per_100g", "PotassiumMgPer100g"},
		{"zinc_mg_per_100g", "ZincMgPer100g"},
		{"copper_mg_per_100g", "CopperMgPer100g"},
		{"manganese_mg_per_100g", "ManganeseMgPer100g"},
		{"selenium_mcg_per_100g", "SeleniumMcgPer100g"},
		{"iodine_mcg_per_100g", "IodineMcgPer100g"},
		{"molybdenum_mcg_per_100g", "MolybdenumMcgPer100g"},
		{"chromium_mcg_per_100g", "ChromiumMcgPer100g"},
		{"fluoride_mg_per_100g", "FluorideMgPer100g"},
		{"chloride_mg_per_100g", "ChlorideMgPer100g"},
		{"omega3_ala_g_per_100g", "Omega3AlaGPer100g"},
		{"omega3_epa_g_per_100g", "Omega3EpaGPer100g"},
		{"omega3_dha_g_per_100g", "Omega3DhaGPer100g"},
		{"omega6_g_per_100g", "Omega6GPer100g"},
		{"alcohol_g_per_100g", "AlcoholGPer100g"},
		{"caffeine_mg_per_100g", "CaffeineMgPer100g"},
		{"creatine_mg_per_100g", "CreatineMgPer100g"},
	}

	originalFields := []NutrientField{
		{"original_serving_grams", "OriginalServingGrams"},
		{"original_calories", "OriginalCalories"},
		{"original_protein_g", "OriginalProteinG"},
		{"original_total_fat_g", "OriginalTotalFatG"},
		{"original_saturated_fat_g", "OriginalSaturatedFatG"},
		{"original_trans_fat_g", "OriginalTransFatG"},
		{"original_monounsaturated_fat_g", "OriginalMonounsaturatedFatG"},
		{"original_polyunsaturated_fat_g", "OriginalPolyunsaturatedFatG"},
		{"original_cholesterol_mg", "OriginalCholesterolMg"},
		{"original_sodium_mg", "OriginalSodiumMg"},
		{"original_total_carbs_g", "OriginalTotalCarbsG"},
		{"original_dietary_fiber_g", "OriginalDietaryFiberG"},
		{"original_total_sugars_g", "OriginalTotalSugarsG"},
		{"original_added_sugars_g", "OriginalAddedSugarsG"},
		{"original_vitamin_a_mcg", "OriginalVitaminAMcg"},
		{"original_vitamin_c_mg", "OriginalVitaminCMg"},
		{"original_vitamin_d_mcg", "OriginalVitaminDMcg"},
		{"original_vitamin_e_mg", "OriginalVitaminEMg"},
		{"original_vitamin_k_mcg", "OriginalVitaminKMcg"},
		{"original_thiamine_mg", "OriginalThiamineMg"},
		{"original_riboflavin_mg", "OriginalRiboflavinMg"},
		{"original_niacin_mg", "OriginalNiacinMg"},
		{"original_vitamin_b6_mg", "OriginalVitaminB6Mg"},
		{"original_folate_mcg", "OriginalFolateMcg"},
		{"original_vitamin_b12_mcg", "OriginalVitaminB12Mcg"},
		{"original_biotin_mcg", "OriginalBiotinMcg"},
		{"original_pantothenic_acid_mg", "OriginalPantothenicAcidMg"},
		{"original_choline_mg", "OriginalCholineMg"},
		{"original_calcium_mg", "OriginalCalciumMg"},
		{"original_iron_mg", "OriginalIronMg"},
		{"original_magnesium_mg", "OriginalMagnesiumMg"},
		{"original_phosphorus_mg", "OriginalPhosphorusMg"},
		{"original_potassium_mg", "OriginalPotassiumMg"},
		{"original_zinc_mg", "OriginalZincMg"},
		{"original_copper_mg", "OriginalCopperMg"},
		{"original_manganese_mg", "OriginalManganeseMg"},
		{"original_selenium_mcg", "OriginalSeleniumMcg"},
		{"original_iodine_mcg", "OriginalIodineMcg"},
		{"original_molybdenum_mcg", "OriginalMolybdenumMcg"},
		{"original_chromium_mcg", "OriginalChromiumMcg"},
		{"original_fluoride_mg", "OriginalFluorideMg"},
		{"original_chloride_mg", "OriginalChlorideMg"},
		{"original_omega3_ala_g", "OriginalOmega3AlaG"},
		{"original_omega3_epa_g", "OriginalOmega3EpaG"},
		{"original_omega3_dha_g", "OriginalOmega3DhaG"},
		{"original_omega6_g", "OriginalOmega6G"},
		{"original_alcohol_g", "OriginalAlcoholG"},
		{"original_caffeine_mg", "OriginalCaffeineMg"},
		{"original_creatine_mg", "OriginalCreatineMg"},
	}

	// Combine both sets
	return append(per100gFields, originalFields...)
}
