// Nutrient field mappings for query builder
// THIS FILE IS GENERATED - DO NOT EDIT MANUALLY
// Generated from nutrients.yaml

package storage

// GetNutrientFields returns all nutrition-related database columns and their corresponding struct field names
func GetNutrientFields() []NutrientField {
	per100gFields := []NutrientField{
		{"calories_per_100g", "CaloriesPer100g"},
		{"protein_g_per_100g", "ProteinPer100g"},
		{"total_fat_g_per_100g", "TotalFatPer100g"},
		{"saturated_fat_g_per_100g", "SaturatedFatPer100g"},
		{"trans_fat_g_per_100g", "TransFatPer100g"},
		{"monounsaturated_fat_g_per_100g", "MonounsaturatedFatPer100g"},
		{"polyunsaturated_fat_g_per_100g", "PolyunsaturatedFatPer100g"},
		{"cholesterol_mg_per_100g", "CholesterolPer100g"},
		{"sodium_mg_per_100g", "SodiumPer100g"},
		{"total_carbs_g_per_100g", "TotalCarbsPer100g"},
		{"dietary_fiber_g_per_100g", "DietaryFiberPer100g"},
		{"total_sugars_g_per_100g", "TotalSugarsPer100g"},
		{"added_sugars_g_per_100g", "AddedSugarsPer100g"},
		{"vitamin_a_mcg_per_100g", "VitaminAPer100g"},
		{"vitamin_c_mg_per_100g", "VitaminCPer100g"},
		{"vitamin_d_mcg_per_100g", "VitaminDPer100g"},
		{"vitamin_e_mg_per_100g", "VitaminEPer100g"},
		{"vitamin_k_mcg_per_100g", "VitaminKPer100g"},
		{"thiamine_mg_per_100g", "ThiaminePer100g"},
		{"riboflavin_mg_per_100g", "RiboflavinPer100g"},
		{"niacin_mg_per_100g", "NiacinPer100g"},
		{"vitamin_b6_mg_per_100g", "VitaminB6Per100g"},
		{"folate_mcg_per_100g", "FolatePer100g"},
		{"vitamin_b12_mcg_per_100g", "VitaminB12Per100g"},
		{"biotin_mcg_per_100g", "BiotinPer100g"},
		{"pantothenic_acid_mg_per_100g", "PantothenicAcidPer100g"},
		{"choline_mg_per_100g", "CholinePer100g"},
		{"calcium_mg_per_100g", "CalciumPer100g"},
		{"iron_mg_per_100g", "IronPer100g"},
		{"magnesium_mg_per_100g", "MagnesiumPer100g"},
		{"phosphorus_mg_per_100g", "PhosphorusPer100g"},
		{"potassium_mg_per_100g", "PotassiumPer100g"},
		{"zinc_mg_per_100g", "ZincPer100g"},
		{"copper_mg_per_100g", "CopperPer100g"},
		{"manganese_mg_per_100g", "ManganesePer100g"},
		{"selenium_mcg_per_100g", "SeleniumPer100g"},
		{"iodine_mcg_per_100g", "IodinePer100g"},
		{"molybdenum_mcg_per_100g", "MolybdenumPer100g"},
		{"chromium_mcg_per_100g", "ChromiumPer100g"},
		{"fluoride_mg_per_100g", "FluoridePer100g"},
		{"chloride_mg_per_100g", "ChloridePer100g"},
		{"omega3_ala_g_per_100g", "Omega3AlaPer100g"},
		{"omega3_epa_g_per_100g", "Omega3EpaPer100g"},
		{"omega3_dha_g_per_100g", "Omega3DhaPer100g"},
		{"omega6_g_per_100g", "Omega6Per100g"},
		{"alcohol_g_per_100g", "AlcoholPer100g"},
		{"caffeine_mg_per_100g", "CaffeinePer100g"},
		{"creatine_mg_per_100g", "CreatinePer100g"},
	}

	originalFields := []NutrientField{
		{"original_serving_grams", "OriginalServingGrams"},
		{"original_calories", "OriginalCalories"},
		{"original_protein_g", "OriginalProtein"},
		{"original_total_fat_g", "OriginalTotalFat"},
		{"original_saturated_fat_g", "OriginalSaturatedFat"},
		{"original_trans_fat_g", "OriginalTransFat"},
		{"original_monounsaturated_fat_g", "OriginalMonounsaturatedFat"},
		{"original_polyunsaturated_fat_g", "OriginalPolyunsaturatedFat"},
		{"original_cholesterol_mg", "OriginalCholesterol"},
		{"original_sodium_mg", "OriginalSodium"},
		{"original_total_carbs_g", "OriginalTotalCarbs"},
		{"original_dietary_fiber_g", "OriginalDietaryFiber"},
		{"original_total_sugars_g", "OriginalTotalSugars"},
		{"original_added_sugars_g", "OriginalAddedSugars"},
		{"original_vitamin_a_mcg", "OriginalVitaminA"},
		{"original_vitamin_c_mg", "OriginalVitaminC"},
		{"original_vitamin_d_mcg", "OriginalVitaminD"},
		{"original_vitamin_e_mg", "OriginalVitaminE"},
		{"original_vitamin_k_mcg", "OriginalVitaminK"},
		{"original_thiamine_mg", "OriginalThiamine"},
		{"original_riboflavin_mg", "OriginalRiboflavin"},
		{"original_niacin_mg", "OriginalNiacin"},
		{"original_vitamin_b6_mg", "OriginalVitaminB6"},
		{"original_folate_mcg", "OriginalFolate"},
		{"original_vitamin_b12_mcg", "OriginalVitaminB12"},
		{"original_biotin_mcg", "OriginalBiotin"},
		{"original_pantothenic_acid_mg", "OriginalPantothenicAcid"},
		{"original_choline_mg", "OriginalCholine"},
		{"original_calcium_mg", "OriginalCalcium"},
		{"original_iron_mg", "OriginalIron"},
		{"original_magnesium_mg", "OriginalMagnesium"},
		{"original_phosphorus_mg", "OriginalPhosphorus"},
		{"original_potassium_mg", "OriginalPotassium"},
		{"original_zinc_mg", "OriginalZinc"},
		{"original_copper_mg", "OriginalCopper"},
		{"original_manganese_mg", "OriginalManganese"},
		{"original_selenium_mcg", "OriginalSelenium"},
		{"original_iodine_mcg", "OriginalIodine"},
		{"original_molybdenum_mcg", "OriginalMolybdenum"},
		{"original_chromium_mcg", "OriginalChromium"},
		{"original_fluoride_mg", "OriginalFluoride"},
		{"original_chloride_mg", "OriginalChloride"},
		{"original_omega3_ala_g", "OriginalOmega3Ala"},
		{"original_omega3_epa_g", "OriginalOmega3Epa"},
		{"original_omega3_dha_g", "OriginalOmega3Dha"},
		{"original_omega6_g", "OriginalOmega6"},
		{"original_alcohol_g", "OriginalAlcohol"},
		{"original_caffeine_mg", "OriginalCaffeine"},
		{"original_creatine_mg", "OriginalCreatine"},
	}

	// Combine both sets
	return append(per100gFields, originalFields...)
}
