package server

// CompleteNutrient represents all nutrition data for a food item (per serving)
// THIS FILE IS GENERATED - DO NOT EDIT MANUALLY
// Generated from nutrients.yaml - see internal/nutrients/generator.go
type CompleteNutrient struct {
	Calories float64 `json:"calories"` // Calories (kcal)
	Protein float64 `json:"protein_g"` // Protein (g)
	TotalFat float64 `json:"total_fat_g"` // Total Fat (g)
	SaturatedFat float64 `json:"saturated_fat_g"` // Saturated Fat (g)
	TransFat float64 `json:"trans_fat_g"` // Trans Fat (g)
	MonounsaturatedFat float64 `json:"monounsaturated_fat_g"` // Monounsaturated Fat (g)
	PolyunsaturatedFat float64 `json:"polyunsaturated_fat_g"` // Polyunsaturated Fat (g)
	Cholesterol float64 `json:"cholesterol_mg"` // Cholesterol (mg)
	Sodium float64 `json:"sodium_mg"` // Sodium (mg)
	TotalCarbs float64 `json:"total_carbs_g"` // Total Carbohydrates (g)
	DietaryFiber float64 `json:"dietary_fiber_g"` // Dietary Fiber (g)
	TotalSugars float64 `json:"total_sugars_g"` // Total Sugars (g)
	AddedSugars float64 `json:"added_sugars_g"` // Added Sugars (g)
	VitaminA float64 `json:"vitamin_a_mcg"` // Vitamin A (mcg)
	VitaminC float64 `json:"vitamin_c_mg"` // Vitamin C (mg)
	VitaminD float64 `json:"vitamin_d_mcg"` // Vitamin D (mcg)
	VitaminE float64 `json:"vitamin_e_mg"` // Vitamin E (mg)
	VitaminK float64 `json:"vitamin_k_mcg"` // Vitamin K (mcg)
	Thiamine float64 `json:"thiamine_mg"` // Thiamine (B1) (mg)
	Riboflavin float64 `json:"riboflavin_mg"` // Riboflavin (B2) (mg)
	Niacin float64 `json:"niacin_mg"` // Niacin (B3) (mg)
	VitaminB6 float64 `json:"vitamin_b6_mg"` // Vitamin B6 (mg)
	Folate float64 `json:"folate_mcg"` // Folate (mcg)
	VitaminB12 float64 `json:"vitamin_b12_mcg"` // Vitamin B12 (mcg)
	Biotin float64 `json:"biotin_mcg"` // Biotin (mcg)
	PantothenicAcid float64 `json:"pantothenic_acid_mg"` // Pantothenic Acid (mg)
	Choline float64 `json:"choline_mg"` // Choline (mg)
	Calcium float64 `json:"calcium_mg"` // Calcium (mg)
	Iron float64 `json:"iron_mg"` // Iron (mg)
	Magnesium float64 `json:"magnesium_mg"` // Magnesium (mg)
	Phosphorus float64 `json:"phosphorus_mg"` // Phosphorus (mg)
	Potassium float64 `json:"potassium_mg"` // Potassium (mg)
	Zinc float64 `json:"zinc_mg"` // Zinc (mg)
	Copper float64 `json:"copper_mg"` // Copper (mg)
	Manganese float64 `json:"manganese_mg"` // Manganese (mg)
	Selenium float64 `json:"selenium_mcg"` // Selenium (mcg)
	Iodine float64 `json:"iodine_mcg"` // Iodine (mcg)
	Molybdenum float64 `json:"molybdenum_mcg"` // Molybdenum (mcg)
	Chromium float64 `json:"chromium_mcg"` // Chromium (mcg)
	Fluoride float64 `json:"fluoride_mg"` // Fluoride (mg)
	Chloride float64 `json:"chloride_mg"` // Chloride (mg)
	Omega3Ala float64 `json:"omega3_ala_g"` // Omega-3 ALA (g)
	Omega3Epa float64 `json:"omega3_epa_g"` // Omega-3 EPA (g)
	Omega3Dha float64 `json:"omega3_dha_g"` // Omega-3 DHA (g)
	Omega6 float64 `json:"omega6_g"` // Omega-6 (g)
	Alcohol float64 `json:"alcohol_g"` // Alcohol (g)
	Caffeine float64 `json:"caffeine_mg"` // Caffeine (mg)
	Creatine float64 `json:"creatine_mg"` // Creatine (mg)
}
