// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExportResponseFormat.
const (
	ExportResponseFormatCsv  ExportResponseFormat = "csv"
	ExportResponseFormatJson ExportResponseFormat = "json"
)

// Defines values for GoalsSource.
const (
	Custom GoalsSource = "custom"
	Dri    GoalsSource = "dri"
)

// Defines values for LifeStageSex.
const (
	LifeStageSexFemale      LifeStageSex = "female"
	LifeStageSexMale        LifeStageSex = "male"
	LifeStageSexUnspecified LifeStageSex = "unspecified"
)

// Defines values for UpdateBiometricsRequestActivityLevel.
const (
	UpdateBiometricsRequestActivityLevelExtraActive      UpdateBiometricsRequestActivityLevel = "extra_active"
	UpdateBiometricsRequestActivityLevelLightlyActive    UpdateBiometricsRequestActivityLevel = "lightly_active"
	UpdateBiometricsRequestActivityLevelModeratelyActive UpdateBiometricsRequestActivityLevel = "moderately_active"
	UpdateBiometricsRequestActivityLevelSedentary        UpdateBiometricsRequestActivityLevel = "sedentary"
	UpdateBiometricsRequestActivityLevelVeryActive       UpdateBiometricsRequestActivityLevel = "very_active"
)

// Defines values for UpdateBiometricsRequestSex.
const (
	UpdateBiometricsRequestSexFemale         UpdateBiometricsRequestSex = "female"
	UpdateBiometricsRequestSexMale           UpdateBiometricsRequestSex = "male"
	UpdateBiometricsRequestSexOther          UpdateBiometricsRequestSex = "other"
	UpdateBiometricsRequestSexPreferNotToSay UpdateBiometricsRequestSex = "prefer_not_to_say"
)

// Defines values for UserSubscriptionTier.
const (
	Free UserSubscriptionTier = "free"
	Pro  UserSubscriptionTier = "pro"
)

// Defines values for UserBiometricsActivityLevel.
const (
	UserBiometricsActivityLevelExtraActive      UserBiometricsActivityLevel = "extra_active"
	UserBiometricsActivityLevelLightlyActive    UserBiometricsActivityLevel = "lightly_active"
	UserBiometricsActivityLevelModeratelyActive UserBiometricsActivityLevel = "moderately_active"
	UserBiometricsActivityLevelSedentary        UserBiometricsActivityLevel = "sedentary"
	UserBiometricsActivityLevelVeryActive       UserBiometricsActivityLevel = "very_active"
)

// Defines values for UserBiometricsSex.
const (
	Female         UserBiometricsSex = "female"
	Male           UserBiometricsSex = "male"
	Other          UserBiometricsSex = "other"
	PreferNotToSay UserBiometricsSex = "prefer_not_to_say"
)

// Defines values for ExportDataParamsFormat.
const (
	ExportDataParamsFormatCsv  ExportDataParamsFormat = "csv"
	ExportDataParamsFormatJson ExportDataParamsFormat = "json"
)

// BiometricsResponse defines model for BiometricsResponse.
type BiometricsResponse struct {
	Biometrics        *UserBiometrics `json:"biometrics,omitempty"`
	CalculatedMetrics *struct {
		// AgeYears Calculated age in years
		AgeYears *int `json:"age_years,omitempty"`

		// Bmi Body Mass Index
		Bmi *float32 `json:"bmi,omitempty"`

		// Bmr Basal Metabolic Rate (calories/day)
		Bmr *float32 `json:"bmr,omitempty"`

		// Tdee Total Daily Energy Expenditure (calories/day)
		Tdee *float32 `json:"tdee,omitempty"`
	} `json:"calculated_metrics,omitempty"`
}

// CompleteNutrient defines model for CompleteNutrient.
type CompleteNutrient struct {
	// AddedSugarsG Added sugars in grams
	AddedSugarsG float32 `json:"added_sugars_g"`

	// BiotinMcg Biotin in micrograms
	BiotinMcg float32 `json:"biotin_mcg"`

	// CalciumMg Calcium in milligrams
	CalciumMg float32 `json:"calcium_mg"`

	// Calories Calories per serving
	Calories float32 `json:"calories"`

	// ChlorideMg Chloride in milligrams
	ChlorideMg float32 `json:"chloride_mg"`

	// CholesterolMg Cholesterol in milligrams
	CholesterolMg float32 `json:"cholesterol_mg"`

	// CholineMg Choline in milligrams
	CholineMg float32 `json:"choline_mg"`

	// ChromiumMcg Chromium in micrograms
	ChromiumMcg float32 `json:"chromium_mcg"`

	// CopperMg Copper in milligrams
	CopperMg float32 `json:"copper_mg"`

	// DietaryFiberG Dietary fiber in grams
	DietaryFiberG float32 `json:"dietary_fiber_g"`

	// FluorideMg Fluoride in milligrams
	FluorideMg float32 `json:"fluoride_mg"`

	// FolateMcg Folate in micrograms
	FolateMcg float32 `json:"folate_mcg"`

	// IodineMcg Iodine in micrograms
	IodineMcg float32 `json:"iodine_mcg"`

	// IronMg Iron in milligrams
	IronMg float32 `json:"iron_mg"`

	// MagnesiumMg Magnesium in milligrams
	MagnesiumMg float32 `json:"magnesium_mg"`

	// ManganeseMg Manganese in milligrams
	ManganeseMg float32 `json:"manganese_mg"`

	// MolybdenumMcg Molybdenum in micrograms
	MolybdenumMcg float32 `json:"molybdenum_mcg"`

	// NiacinMg Niacin (B3) in milligrams
	NiacinMg float32 `json:"niacin_mg"`

	// PantothenicAcidMg Pantothenic Acid (B5) in milligrams
	PantothenicAcidMg float32 `json:"pantothenic_acid_mg"`

	// PhosphorusMg Phosphorus in milligrams
	PhosphorusMg float32 `json:"phosphorus_mg"`

	// PotassiumMg Potassium in milligrams
	PotassiumMg float32 `json:"potassium_mg"`

	// ProteinG Protein in grams
	ProteinG float32 `json:"protein_g"`

	// RiboflavinMg Riboflavin (B2) in milligrams
	RiboflavinMg float32 `json:"riboflavin_mg"`

	// SaturatedFatG Saturated fat in grams
	SaturatedFatG float32 `json:"saturated_fat_g"`

	// SeleniumMcg Selenium in micrograms
	SeleniumMcg float32 `json:"selenium_mcg"`

	// SodiumMg Sodium in milligrams
	SodiumMg float32 `json:"sodium_mg"`

	// ThiamineMg Thiamine (B1) in milligrams
	ThiamineMg float32 `json:"thiamine_mg"`

	// TotalCarbsG Total carbohydrates in grams
	TotalCarbsG float32 `json:"total_carbs_g"`

	// TotalFatG Total fat in grams
	TotalFatG float32 `json:"total_fat_g"`

	// TotalSugarsG Total sugars in grams
	TotalSugarsG float32 `json:"total_sugars_g"`

	// TransFatG Trans fat in grams
	TransFatG float32 `json:"trans_fat_g"`

	// VitaminAMcg Vitamin A in micrograms
	VitaminAMcg float32 `json:"vitamin_a_mcg"`

	// VitaminB12Mcg Vitamin B12 in micrograms
	VitaminB12Mcg float32 `json:"vitamin_b12_mcg"`

	// VitaminB6Mg Vitamin B6 in milligrams
	VitaminB6Mg float32 `json:"vitamin_b6_mg"`

	// VitaminCMg Vitamin C in milligrams
	VitaminCMg float32 `json:"vitamin_c_mg"`

	// VitaminDMcg Vitamin D in micrograms
	VitaminDMcg float32 `json:"vitamin_d_mcg"`

	// VitaminEMg Vitamin E in milligrams
	VitaminEMg float32 `json:"vitamin_e_mg"`

	// VitaminKMcg Vitamin K in micrograms
	VitaminKMcg float32 `json:"vitamin_k_mcg"`

	// ZincMg Zinc in milligrams
	ZincMg float32 `json:"zinc_mg"`
}

// Consumption defines model for Consumption.
type Consumption struct {
	// CreatedAt Timestamp when consumption was logged
	CreatedAt time.Time `json:"created_at"`

	// Id Consumption ID
	Id      string              `json:"id"`
	Items   []ItemWithNutrition `json:"items"`
	Summary Summary             `json:"summary"`

	// Transcript Original transcribed text
	Transcript string `json:"transcript"`

	// UserId User ID who logged this consumption
	UserId string `json:"user_id"`
}

// ConsumptionResponse defines model for ConsumptionResponse.
type ConsumptionResponse struct {
	// Id Consumption ID (for future edits/deletes)
	Id string `json:"id"`

	// Items Items with complete nutrition information
	Items []ItemWithNutrition `json:"items"`

	// ParsedItems Items parsed from transcript (without nutrition data)
	ParsedItems []Item `json:"parsedItems"`

	// RequestId Request identifier for tracking
	RequestId string  `json:"request_id"`
	Summary   Summary `json:"summary"`

	// Transcript Transcribed text from audio
	Transcript string `json:"transcript"`
}

// ConsumptionsResponse defines model for ConsumptionsResponse.
type ConsumptionsResponse struct {
	Consumptions []Consumption `json:"consumptions"`

	// Count Number of consumptions returned
	Count int  `json:"count"`
	User  User `json:"user"`
}

// DailySummary defines model for DailySummary.
type DailySummary struct {
	// Calories Total calories for the day
	Calories float32 `json:"calories"`

	// ConsumptionCount Number of consumptions on this date
	ConsumptionCount int `json:"consumption_count"`

	// Date Date for this daily summary
	Date time.Time `json:"date"`

	// FiberG Total fiber in grams for the day
	FiberG float32 `json:"fiber_g"`

	// ProteinG Total protein in grams for the day
	ProteinG float32 `json:"protein_g"`

	// SodiumMg Total sodium in milligrams for the day
	SodiumMg float32 `json:"sodium_mg"`

	// TotalCarbsG Total carbohydrates in grams for the day
	TotalCarbsG float32 `json:"total_carbs_g"`

	// TotalFatG Total fat in grams for the day
	TotalFatG float32 `json:"total_fat_g"`
}

// DataPoint defines model for DataPoint.
type DataPoint struct {
	// Date Date for this data point
	Date time.Time `json:"date"`

	// Value Nutrient value for this date
	Value float32 `json:"value"`
}

// DeleteResponse defines model for DeleteResponse.
type DeleteResponse struct {
	// Id ID of the deleted consumption
	Id string `json:"id"`

	// Message Confirmation message
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Error Error message
	Error string `json:"error"`

	// Stack Stack trace (only in debug mode)
	Stack *[]string `json:"stack,omitempty"`

	// Timestamp Timestamp when the error occurred
	Timestamp time.Time `json:"timestamp"`

	// TraceId Request trace ID
	TraceId *string `json:"trace_id,omitempty"`
}

// ExportResponse defines model for ExportResponse.
type ExportResponse struct {
	DateRange struct {
		End   *time.Time `json:"end,omitempty"`
		Start *time.Time `json:"start,omitempty"`
	} `json:"date_range"`

	// Format Export format used
	Format ExportResponseFormat `json:"format"`

	// Series Time series data for each requested metric
	Series map[string][]DataPoint `json:"series"`
	User   User                   `json:"user"`
}

// ExportResponseFormat Export format used
type ExportResponseFormat string

// GoalSetSummary defines model for GoalSetSummary.
type GoalSetSummary struct {
	// CreatedAt When the goal set was created
	CreatedAt time.Time `json:"created_at"`

	// Name Name of the goal set
	Name string `json:"name"`

	// UpdatedAt When the goal set was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// GoalSetsResponse defines model for GoalSetsResponse.
type GoalSetsResponse struct {
	// ActiveGoalName Name of the currently active goal set
	ActiveGoalName string `json:"active_goal_name"`

	// GoalSets List of all available goal sets
	GoalSets []GoalSetSummary `json:"goal_sets"`
	User     User             `json:"user"`
}

// Goals defines model for Goals.
type Goals struct {
	// CustomName Name of the custom goal set (only present when source is "custom")
	CustomName *string   `json:"custom_name,omitempty"`
	LifeStage  LifeStage `json:"life_stage"`

	// Source Source of the goals (DRI defaults or custom overrides)
	Source GoalsSource `json:"source"`

	// Targets Target amounts for each nutrient
	Targets map[string]float32 `json:"targets"`

	// Units Units for each nutrient
	Units map[string]string `json:"units"`

	// UpperLimits Upper limit amounts for each nutrient (where defined)
	UpperLimits map[string]float32 `json:"upper_limits"`
}

// GoalsSource Source of the goals (DRI defaults or custom overrides)
type GoalsSource string

// GoalsResponse defines model for GoalsResponse.
type GoalsResponse struct {
	Goals Goals `json:"goals"`
	User  User  `json:"user"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// Item defines model for Item.
type Item struct {
	// Brand Brand name
	Brand *string `json:"brand"`

	// Grams Weight in grams (standardized internally)
	Grams float32 `json:"grams"`

	// Name Name of the food item
	Name      string            `json:"name"`
	Nutrients *CompleteNutrient `json:"nutrients,omitempty"`

	// UserQuantity Original user input quantity for display
	UserQuantity *float32 `json:"user_quantity"`

	// UserUnit Original user input unit for display
	UserUnit *string `json:"user_unit"`
}

// ItemWithNutrition defines model for ItemWithNutrition.
type ItemWithNutrition struct {
	Item Item `json:"item"`

	// Note Additional note (e.g., if nutrition data unavailable)
	Note *string `json:"note,omitempty"`
}

// LifeStage defines model for LifeStage.
type LifeStage struct {
	// AgeBracket Age bracket used for DRI lookup
	AgeBracket string `json:"age_bracket"`

	// Sex User sex for DRI calculation
	Sex LifeStageSex `json:"sex"`
}

// LifeStageSex User sex for DRI calculation
type LifeStageSex string

// NutritionSummary defines model for NutritionSummary.
type NutritionSummary struct {
	// AvgCaloriesPerDay Average calories per day
	AvgCaloriesPerDay float32 `json:"avg_calories_per_day"`

	// AvgCarbsPerDay Average carbs per day in grams
	AvgCarbsPerDay float32 `json:"avg_carbs_per_day"`

	// AvgFatPerDay Average fat per day in grams
	AvgFatPerDay float32 `json:"avg_fat_per_day"`

	// AvgFiberPerDay Average fiber per day in grams
	AvgFiberPerDay float32 `json:"avg_fiber_per_day"`

	// AvgProteinPerDay Average protein per day in grams
	AvgProteinPerDay float32 `json:"avg_protein_per_day"`

	// AvgSodiumPerDay Average sodium per day in milligrams
	AvgSodiumPerDay float32 `json:"avg_sodium_per_day"`

	// ConsumptionCount Total number of consumptions in the period
	ConsumptionCount int `json:"consumption_count"`

	// DailyBreakdown Daily nutrition breakdown
	DailyBreakdown []DailySummary `json:"daily_breakdown"`

	// EndDate End date of the summary period
	EndDate time.Time `json:"end_date"`

	// StartDate Start date of the summary period
	StartDate time.Time `json:"start_date"`

	// TotalAddedSugarsG Total added sugars in grams
	TotalAddedSugarsG float32 `json:"total_added_sugars_g"`

	// TotalBiotinMcg Total biotin in micrograms
	TotalBiotinMcg float32 `json:"total_biotin_mcg"`

	// TotalCalciumMg Total calcium in milligrams
	TotalCalciumMg float32 `json:"total_calcium_mg"`

	// TotalCalories Total calories consumed
	TotalCalories float32 `json:"total_calories"`

	// TotalCarbsG Total carbohydrates in grams
	TotalCarbsG float32 `json:"total_carbs_g"`

	// TotalChlorideMg Total chloride in milligrams
	TotalChlorideMg float32 `json:"total_chloride_mg"`

	// TotalCholesterolMg Total cholesterol in milligrams
	TotalCholesterolMg float32 `json:"total_cholesterol_mg"`

	// TotalCholineMg Total choline in milligrams
	TotalCholineMg float32 `json:"total_choline_mg"`

	// TotalChromiumMcg Total chromium in micrograms
	TotalChromiumMcg float32 `json:"total_chromium_mcg"`

	// TotalCopperMg Total copper in milligrams
	TotalCopperMg float32 `json:"total_copper_mg"`

	// TotalFatG Total fat in grams
	TotalFatG float32 `json:"total_fat_g"`

	// TotalFiberG Total fiber in grams
	TotalFiberG float32 `json:"total_fiber_g"`

	// TotalFluorideMg Total fluoride in milligrams
	TotalFluorideMg float32 `json:"total_fluoride_mg"`

	// TotalFolateMcg Total folate in micrograms
	TotalFolateMcg float32 `json:"total_folate_mcg"`

	// TotalIodineMcg Total iodine in micrograms
	TotalIodineMcg float32 `json:"total_iodine_mcg"`

	// TotalIronMg Total iron in milligrams
	TotalIronMg float32 `json:"total_iron_mg"`

	// TotalMagnesiumMg Total magnesium in milligrams
	TotalMagnesiumMg float32 `json:"total_magnesium_mg"`

	// TotalManganeseMg Total manganese in milligrams
	TotalManganeseMg float32 `json:"total_manganese_mg"`

	// TotalMolybdenumMcg Total molybdenum in micrograms
	TotalMolybdenumMcg float32 `json:"total_molybdenum_mcg"`

	// TotalNiacinMg Total niacin (B3) in milligrams
	TotalNiacinMg float32 `json:"total_niacin_mg"`

	// TotalPantothenicAcidMg Total pantothenic acid (B5) in milligrams
	TotalPantothenicAcidMg float32 `json:"total_pantothenic_acid_mg"`

	// TotalPhosphorusMg Total phosphorus in milligrams
	TotalPhosphorusMg float32 `json:"total_phosphorus_mg"`

	// TotalPotassiumMg Total potassium in milligrams
	TotalPotassiumMg float32 `json:"total_potassium_mg"`

	// TotalProteinG Total protein in grams
	TotalProteinG float32 `json:"total_protein_g"`

	// TotalRiboflavinMg Total riboflavin (B2) in milligrams
	TotalRiboflavinMg float32 `json:"total_riboflavin_mg"`

	// TotalSaturatedFatG Total saturated fat in grams
	TotalSaturatedFatG float32 `json:"total_saturated_fat_g"`

	// TotalSeleniumMcg Total selenium in micrograms
	TotalSeleniumMcg float32 `json:"total_selenium_mcg"`

	// TotalSodiumMg Total sodium in milligrams
	TotalSodiumMg float32 `json:"total_sodium_mg"`

	// TotalSugarsG Total sugars in grams
	TotalSugarsG float32 `json:"total_sugars_g"`

	// TotalThiamineMg Total thiamine (B1) in milligrams
	TotalThiamineMg float32 `json:"total_thiamine_mg"`

	// TotalTransFatG Total trans fat in grams
	TotalTransFatG float32 `json:"total_trans_fat_g"`

	// TotalVitaminAMcg Total vitamin A in micrograms
	TotalVitaminAMcg float32 `json:"total_vitamin_a_mcg"`

	// TotalVitaminB12Mcg Total vitamin B12 in micrograms
	TotalVitaminB12Mcg float32 `json:"total_vitamin_b12_mcg"`

	// TotalVitaminB6Mg Total vitamin B6 in milligrams
	TotalVitaminB6Mg float32 `json:"total_vitamin_b6_mg"`

	// TotalVitaminCMg Total vitamin C in milligrams
	TotalVitaminCMg float32 `json:"total_vitamin_c_mg"`

	// TotalVitaminDMcg Total vitamin D in micrograms
	TotalVitaminDMcg float32 `json:"total_vitamin_d_mcg"`

	// TotalVitaminEMg Total vitamin E in milligrams
	TotalVitaminEMg float32 `json:"total_vitamin_e_mg"`

	// TotalVitaminKMcg Total vitamin K in micrograms
	TotalVitaminKMcg float32 `json:"total_vitamin_k_mcg"`

	// TotalZincMg Total zinc in milligrams
	TotalZincMg float32 `json:"total_zinc_mg"`

	// UserId User ID
	UserId string `json:"user_id"`
}

// NutritionSummaryResponse defines model for NutritionSummaryResponse.
type NutritionSummaryResponse struct {
	DateRange struct {
		End   *time.Time `json:"end,omitempty"`
		Start *time.Time `json:"start,omitempty"`
	} `json:"date_range"`

	// Days Number of days in the summary
	Days    int              `json:"days"`
	Summary NutritionSummary `json:"summary"`
	User    User             `json:"user"`
}

// SetActiveGoalRequest defines model for SetActiveGoalRequest.
type SetActiveGoalRequest struct {
	// Name Name of the goal set to make active
	Name string `json:"name"`
}

// Summary defines model for Summary.
type Summary struct {
	// DailyValues Daily value amounts used for calculations
	DailyValues map[string]float32 `json:"daily_values"`

	// PercentOfDaily Percentage of daily values for each nutrient
	PercentOfDaily map[string]int   `json:"percent_of_daily"`
	Totals         CompleteNutrient `json:"totals"`
}

// TrendsResponse defines model for TrendsResponse.
type TrendsResponse struct {
	DateRange struct {
		End   *time.Time `json:"end,omitempty"`
		Start *time.Time `json:"start,omitempty"`
	} `json:"date_range"`

	// Days Number of days in the time series
	Days int `json:"days"`

	// Series Time series data for each requested metric
	Series map[string][]DataPoint `json:"series"`
	User   User                   `json:"user"`
}

// UpdateBiometricsRequest defines model for UpdateBiometricsRequest.
type UpdateBiometricsRequest struct {
	// ActivityLevel Physical activity level
	ActivityLevel *UpdateBiometricsRequestActivityLevel `json:"activity_level,omitempty"`

	// BirthDate Date of birth
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// HeightCm Height in centimeters
	HeightCm *float32 `json:"height_cm,omitempty"`

	// Sex Biological sex for DRI calculations
	Sex *UpdateBiometricsRequestSex `json:"sex,omitempty"`

	// WeightKg Weight in kilograms
	WeightKg *float32 `json:"weight_kg,omitempty"`
}

// UpdateBiometricsRequestActivityLevel Physical activity level
type UpdateBiometricsRequestActivityLevel string

// UpdateBiometricsRequestSex Biological sex for DRI calculations
type UpdateBiometricsRequestSex string

// UpdateConsumptionRequest defines model for UpdateConsumptionRequest.
type UpdateConsumptionRequest struct {
	// Items Updated items with nutrition information
	Items []ItemWithNutrition `json:"items"`
}

// UpdateGoalsRequest defines model for UpdateGoalsRequest.
type UpdateGoalsRequest struct {
	// Name Custom name for the goal set (required for managing multiple goal sets)
	Name string `json:"name"`

	// Overrides Custom nutrition goal overrides
	Overrides map[string]float32 `json:"overrides"`
}

// User defines model for User.
type User struct {
	// AvatarUrl User avatar/profile image URL
	AvatarUrl *string `json:"avatar_url"`

	// CreatedAt User creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Email User email address
	Email string `json:"email"`

	// FullName User's full display name
	FullName *string `json:"full_name"`

	// Handle Unique user handle/username
	Handle string `json:"handle"`

	// Id User ID (auth.users.id UUID for Supabase)
	Id string `json:"id"`

	// SubscriptionTier User subscription level
	SubscriptionTier UserSubscriptionTier `json:"subscription_tier"`
}

// UserSubscriptionTier User subscription level
type UserSubscriptionTier string

// UserBiometrics defines model for UserBiometrics.
type UserBiometrics struct {
	// ActivityLevel Physical activity level
	ActivityLevel *UserBiometricsActivityLevel `json:"activity_level,omitempty"`

	// BirthDate Date of birth
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// HeightCm Height in centimeters
	HeightCm *float32 `json:"height_cm,omitempty"`

	// Sex Biological sex for DRI calculations
	Sex *UserBiometricsSex `json:"sex,omitempty"`

	// WeightKg Weight in kilograms
	WeightKg *float32 `json:"weight_kg,omitempty"`
}

// UserBiometricsActivityLevel Physical activity level
type UserBiometricsActivityLevel string

// UserBiometricsSex Biological sex for DRI calculations
type UserBiometricsSex string

// CreateConsumptionMultipartBody defines parameters for CreateConsumption.
type CreateConsumptionMultipartBody struct {
	// Audio Audio file (webm, opus, mp3, wav)
	Audio openapi_types.File `json:"audio"`
}

// ExportDataParams defines parameters for ExportData.
type ExportDataParams struct {
	// Format Export format
	Format ExportDataParamsFormat `form:"format" json:"format"`

	// Start Start date (RFC3339 format)
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End End date (RFC3339 format)
	End *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Metrics Comma-separated list of metrics to include (defaults to common macros)
	Metrics *string `form:"metrics,omitempty" json:"metrics,omitempty"`
}

// ExportDataParamsFormat defines parameters for ExportData.
type ExportDataParamsFormat string

// GetGoalsParams defines parameters for GetGoals.
type GetGoalsParams struct {
	// GoalName Name of the specific goal set to retrieve. If not provided, returns the active goal set.
	GoalName *string `form:"goal_name,omitempty" json:"goal_name,omitempty"`
}

// GetNutritionSummaryParams defines parameters for GetNutritionSummary.
type GetNutritionSummaryParams struct {
	// Start Start date (RFC3339 format)
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End End date (RFC3339 format)
	End *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Days Number of days to look back from today
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// GetTrendsParams defines parameters for GetTrends.
type GetTrendsParams struct {
	// Metrics Comma-separated list of metrics to include
	Metrics *string `form:"metrics,omitempty" json:"metrics,omitempty"`

	// Start Start date (RFC3339 format)
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End End date (RFC3339 format)
	End *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Days Number of days to look back from today (alternative to start/end)
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// UpdateUserBiometricsJSONRequestBody defines body for UpdateUserBiometrics for application/json ContentType.
type UpdateUserBiometricsJSONRequestBody = UpdateBiometricsRequest

// CreateConsumptionMultipartRequestBody defines body for CreateConsumption for multipart/form-data ContentType.
type CreateConsumptionMultipartRequestBody CreateConsumptionMultipartBody

// UpdateConsumptionJSONRequestBody defines body for UpdateConsumption for application/json ContentType.
type UpdateConsumptionJSONRequestBody = UpdateConsumptionRequest

// UpdateGoalsJSONRequestBody defines body for UpdateGoals for application/json ContentType.
type UpdateGoalsJSONRequestBody = UpdateGoalsRequest

// SetActiveGoalSetJSONRequestBody defines body for SetActiveGoalSet for application/json ContentType.
type SetActiveGoalSetJSONRequestBody = SetActiveGoalRequest
