// Code generated by oapi-codegen. DO NOT EDIT.
// This file is a placeholder - the actual file will be generated from api/openapi.yaml

package api

import (
	"time"
)

// ErrorResponse defines the error response structure
type ErrorResponse struct {
	Error     string    `json:"error"`
	Code      int       `json:"code"`
	Timestamp time.Time `json:"timestamp"`
	Stack     *[]string `json:"stack,omitempty"`
	TraceID   *string   `json:"trace_id,omitempty"`
}

// HealthResponse defines the health check response
type HealthResponse struct {
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// Item represents a food item
type Item struct {
	Name      string             `json:"name"`
	Quantity  *float64           `json:"quantity,omitempty"`
	Unit      *string            `json:"unit,omitempty"`
	Brand     *string            `json:"brand,omitempty"`
	Nutrients *CompleteNutrient  `json:"nutrients,omitempty"`
}

// CompleteNutrient contains nutrition information
type CompleteNutrient struct {
	Calories       float64 `json:"calories"`
	ProteinG       float64 `json:"protein_g"`
	TotalFatG      float64 `json:"total_fat_g"`
	SaturatedFatG  float64 `json:"saturated_fat_g"`
	TransFatG      float64 `json:"trans_fat_g"`
	CholesterolMg  float64 `json:"cholesterol_mg"`
	SodiumMg       float64 `json:"sodium_mg"`
	TotalCarbsG    float64 `json:"total_carbs_g"`
	DietaryFiberG  float64 `json:"dietary_fiber_g"`
	TotalSugarsG   float64 `json:"total_sugars_g"`
	AddedSugarsG   float64 `json:"added_sugars_g"`
	VitaminAMcg    float64 `json:"vitamin_a_mcg"`
	VitaminCMg     float64 `json:"vitamin_c_mg"`
	VitaminDMcg    float64 `json:"vitamin_d_mcg"`
	VitaminEMg     float64 `json:"vitamin_e_mg"`
	VitaminKMcg    float64 `json:"vitamin_k_mcg"`
	ThiamineMg     float64 `json:"thiamine_mg"`
	RiboflavinMg   float64 `json:"riboflavin_mg"`
	NiacinMg       float64 `json:"niacin_mg"`
	VitaminB6Mg    float64 `json:"vitamin_b6_mg"`
	FolateMcg      float64 `json:"folate_mcg"`
	VitaminB12Mcg  float64 `json:"vitamin_b12_mcg"`
	CalciumMg      float64 `json:"calcium_mg"`
	IronMg         float64 `json:"iron_mg"`
	MagnesiumMg    float64 `json:"magnesium_mg"`
	PhosphorusMg   float64 `json:"phosphorus_mg"`
	PotassiumMg    float64 `json:"potassium_mg"`
	ZincMg         float64 `json:"zinc_mg"`
	CopperMg       float64 `json:"copper_mg"`
	ManganeseMg    float64 `json:"manganese_mg"`
	SeleniumMcg    float64 `json:"selenium_mcg"`
}

// ItemWithNutrition represents an item with optional nutrition note
type ItemWithNutrition struct {
	Item Item    `json:"item"`
	Note *string `json:"note,omitempty"`
}

// Summary contains nutrition summary data
type Summary struct {
	Totals          CompleteNutrient   `json:"totals"`
	PercentOfDaily  map[string]int     `json:"percent_of_daily"`
	DailyValues     map[string]float64 `json:"daily_values"`
}

// ConsumptionResponse defines the response for consumption endpoint
type ConsumptionResponse struct {
	Transcript   string               `json:"transcript"`
	ParsedItems  []Item               `json:"parsedItems"`
	Items        []ItemWithNutrition  `json:"items"`
	Summary      Summary              `json:"summary"`
	RequestID    string               `json:"request_id"`
}

// User represents a user
type User struct {
	ID               string    `json:"id"`
	Provider         string    `json:"provider"`
	Subject          string    `json:"subject"`
	Email            string    `json:"email"`
	SubscriptionTier string    `json:"subscription_tier"`
	CreatedAt        time.Time `json:"created_at"`
}

// Consumption represents a logged consumption
type Consumption struct {
	ID        string               `json:"id"`
	UserID    string               `json:"user_id"`
	Transcript string              `json:"transcript"`
	Items     []ItemWithNutrition  `json:"items"`
	Summary   Summary              `json:"summary"`
	CreatedAt time.Time            `json:"created_at"`
}

// ConsumptionsResponse defines the response for consumptions list endpoint
type ConsumptionsResponse struct {
	Consumptions []Consumption `json:"consumptions"`
	User         User          `json:"user"`
	Count        int           `json:"count"`
}

// DailySummary represents nutrition data for a single day
type DailySummary struct {
	Date             time.Time `json:"date"`
	ConsumptionCount int       `json:"consumption_count"`
	Calories         float64   `json:"calories"`
	ProteinG         float64   `json:"protein_g"`
	TotalFatG        float64   `json:"total_fat_g"`
	TotalCarbsG      float64   `json:"total_carbs_g"`
	FiberG           float64   `json:"fiber_g"`
	SodiumMg         float64   `json:"sodium_mg"`
}

// NutritionSummary represents aggregated nutrition data
type NutritionSummary struct {
	UserID              string         `json:"user_id"`
	StartDate           time.Time      `json:"start_date"`
	EndDate             time.Time      `json:"end_date"`
	ConsumptionCount    int            `json:"consumption_count"`
	TotalCalories       float64        `json:"total_calories"`
	TotalProteinG       float64        `json:"total_protein_g"`
	TotalFatG           float64        `json:"total_fat_g"`
	TotalCarbsG         float64        `json:"total_carbs_g"`
	TotalFiberG         float64        `json:"total_fiber_g"`
	TotalSodiumMg       float64        `json:"total_sodium_mg"`
	AvgCaloriesPerDay   float64        `json:"avg_calories_per_day"`
	AvgProteinPerDay    float64        `json:"avg_protein_per_day"`
	AvgFatPerDay        float64        `json:"avg_fat_per_day"`
	AvgCarbsPerDay      float64        `json:"avg_carbs_per_day"`
	AvgFiberPerDay      float64        `json:"avg_fiber_per_day"`
	AvgSodiumPerDay     float64        `json:"avg_sodium_per_day"`
	DailyBreakdown      []DailySummary `json:"daily_breakdown"`
}

// NutritionSummaryResponse defines the response for nutrition summary endpoint
type NutritionSummaryResponse struct {
	Summary   NutritionSummary `json:"summary"`
	User      User             `json:"user"`
	Days      int              `json:"days"`
	DateRange struct {
		Start time.Time `json:"start"`
		End   time.Time `json:"end"`
	} `json:"date_range"`
}