// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for APIKeyScope.
const (
	APIKeyScopeRead      APIKeyScope = "read"
	APIKeyScopeReadWrite APIKeyScope = "read_write"
)

// Defines values for CreateAPIKeyRequestScope.
const (
	CreateAPIKeyRequestScopeRead      CreateAPIKeyRequestScope = "read"
	CreateAPIKeyRequestScopeReadWrite CreateAPIKeyRequestScope = "read_write"
)

// Defines values for ExportResponseFormat.
const (
	ExportResponseFormatCsv  ExportResponseFormat = "csv"
	ExportResponseFormatJson ExportResponseFormat = "json"
)

// Defines values for GoalSetSummaryCategory.
const (
	GoalSetSummaryCategoryCustom  GoalSetSummaryCategory = "custom"
	GoalSetSummaryCategoryFitness GoalSetSummaryCategory = "fitness"
	GoalSetSummaryCategoryHealth  GoalSetSummaryCategory = "health"
	GoalSetSummaryCategoryWeight  GoalSetSummaryCategory = "weight"
)

// Defines values for GoalsSource.
const (
	GoalsSourceCustom GoalsSource = "custom"
	GoalsSourceDri    GoalsSource = "dri"
)

// Defines values for LifeStageSex.
const (
	LifeStageSexFemale      LifeStageSex = "female"
	LifeStageSexMale        LifeStageSex = "male"
	LifeStageSexUnspecified LifeStageSex = "unspecified"
)

// Defines values for UpdateBiometricsRequestActivityLevel.
const (
	UpdateBiometricsRequestActivityLevelExtraActive      UpdateBiometricsRequestActivityLevel = "extra_active"
	UpdateBiometricsRequestActivityLevelLightlyActive    UpdateBiometricsRequestActivityLevel = "lightly_active"
	UpdateBiometricsRequestActivityLevelModeratelyActive UpdateBiometricsRequestActivityLevel = "moderately_active"
	UpdateBiometricsRequestActivityLevelSedentary        UpdateBiometricsRequestActivityLevel = "sedentary"
	UpdateBiometricsRequestActivityLevelVeryActive       UpdateBiometricsRequestActivityLevel = "very_active"
)

// Defines values for UpdateBiometricsRequestSex.
const (
	UpdateBiometricsRequestSexFemale         UpdateBiometricsRequestSex = "female"
	UpdateBiometricsRequestSexMale           UpdateBiometricsRequestSex = "male"
	UpdateBiometricsRequestSexOther          UpdateBiometricsRequestSex = "other"
	UpdateBiometricsRequestSexPreferNotToSay UpdateBiometricsRequestSex = "prefer_not_to_say"
)

// Defines values for UpdateGoalsRequestCategory.
const (
	Custom  UpdateGoalsRequestCategory = "custom"
	Fitness UpdateGoalsRequestCategory = "fitness"
	Health  UpdateGoalsRequestCategory = "health"
	Weight  UpdateGoalsRequestCategory = "weight"
)

// Defines values for UserSubscriptionTier.
const (
	Free UserSubscriptionTier = "free"
	Pro  UserSubscriptionTier = "pro"
)

// Defines values for UserBiometricsActivityLevel.
const (
	UserBiometricsActivityLevelExtraActive      UserBiometricsActivityLevel = "extra_active"
	UserBiometricsActivityLevelLightlyActive    UserBiometricsActivityLevel = "lightly_active"
	UserBiometricsActivityLevelModeratelyActive UserBiometricsActivityLevel = "moderately_active"
	UserBiometricsActivityLevelSedentary        UserBiometricsActivityLevel = "sedentary"
	UserBiometricsActivityLevelVeryActive       UserBiometricsActivityLevel = "very_active"
)

// Defines values for UserBiometricsSex.
const (
	Female         UserBiometricsSex = "female"
	Male           UserBiometricsSex = "male"
	Other          UserBiometricsSex = "other"
	PreferNotToSay UserBiometricsSex = "prefer_not_to_say"
)

// Defines values for GetConsumptionsParamsMatch.
const (
	GetConsumptionsParamsMatchAll GetConsumptionsParamsMatch = "all"
	GetConsumptionsParamsMatchAny GetConsumptionsParamsMatch = "any"
)

// Defines values for GetEventsParamsMatch.
const (
	GetEventsParamsMatchAll GetEventsParamsMatch = "all"
	GetEventsParamsMatchAny GetEventsParamsMatch = "any"
)

// Defines values for ExportDataParamsFormat.
const (
	ExportDataParamsFormatCsv  ExportDataParamsFormat = "csv"
	ExportDataParamsFormatJson ExportDataParamsFormat = "json"
)

// Defines values for GetGoalsParamsSource.
const (
	Auto GetGoalsParamsSource = "auto"
	Dri  GetGoalsParamsSource = "dri"
)

// APIKey defines model for APIKey.
type APIKey struct {
	// CreatedAt When the API key was created
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt When the API key expires (null for no expiration)
	ExpiresAt *time.Time `json:"expires_at"`

	// Id Unique identifier for the API key
	Id string `json:"id"`

	// LastUsedAt When the API key was last used
	LastUsedAt *time.Time `json:"last_used_at"`

	// Name User-defined name for the key
	Name string `json:"name"`

	// Prefix Visible prefix for identification (e.g., noot_abc123)
	Prefix string `json:"prefix"`

	// RevokedAt When the API key was revoked (null if active)
	RevokedAt *time.Time `json:"revoked_at"`

	// Scope Permissions scope for the API key
	Scope APIKeyScope `json:"scope"`

	// UserId ID of the user who owns this key
	UserId string `json:"user_id"`
}

// APIKeyScope Permissions scope for the API key
type APIKeyScope string

// APIKeysResponse defines model for APIKeysResponse.
type APIKeysResponse struct {
	// ApiKeys List of API keys (secrets not included)
	ApiKeys []APIKey `json:"api_keys"`
}

// AddFavoriteRequest defines model for AddFavoriteRequest.
type AddFavoriteRequest struct {
	// ConsumptionId ID of the consumption to add to favorites
	ConsumptionId string `json:"consumption_id"`
}

// AssignLabelsRequest defines model for AssignLabelsRequest.
type AssignLabelsRequest struct {
	// Ids Array of label IDs to assign
	Ids []string `json:"ids"`
}

// BiometricsResponse defines model for BiometricsResponse.
type BiometricsResponse struct {
	Biometrics        *UserBiometrics `json:"biometrics,omitempty"`
	CalculatedMetrics *struct {
		// AgeYears Calculated age in years
		AgeYears *int `json:"age_years,omitempty"`

		// Bmi Body Mass Index
		Bmi *float32 `json:"bmi,omitempty"`

		// Bmr Basal Metabolic Rate (calories/day)
		Bmr *float32 `json:"bmr,omitempty"`

		// Tdee Total Daily Energy Expenditure (calories/day)
		Tdee *float32 `json:"tdee,omitempty"`
	} `json:"calculated_metrics,omitempty"`
}

// CompleteNutrient defines model for CompleteNutrient.
type CompleteNutrient struct {
	// AddedSugarsG Added sugars in grams
	AddedSugarsG float32 `json:"added_sugars_g"`

	// AlcoholG Alcohol in grams
	AlcoholG float32 `json:"alcohol_g"`

	// BiotinMcg Biotin in micrograms
	BiotinMcg float32 `json:"biotin_mcg"`

	// CaffeineMg Caffeine in milligrams
	CaffeineMg float32 `json:"caffeine_mg"`

	// CalciumMg Calcium in milligrams
	CalciumMg float32 `json:"calcium_mg"`

	// Calories Calories per serving
	Calories float32 `json:"calories"`

	// ChlorideMg Chloride in milligrams
	ChlorideMg float32 `json:"chloride_mg"`

	// CholesterolMg Cholesterol in milligrams
	CholesterolMg float32 `json:"cholesterol_mg"`

	// CholineMg Choline in milligrams
	CholineMg float32 `json:"choline_mg"`

	// ChromiumMcg Chromium in micrograms
	ChromiumMcg float32 `json:"chromium_mcg"`

	// CopperMg Copper in milligrams
	CopperMg float32 `json:"copper_mg"`

	// CreatineMg Creatine in milligrams
	CreatineMg float32 `json:"creatine_mg"`

	// DietaryFiberG Dietary fiber in grams
	DietaryFiberG float32 `json:"dietary_fiber_g"`

	// FluorideMg Fluoride in milligrams
	FluorideMg float32 `json:"fluoride_mg"`

	// FolateMcg Folate in micrograms
	FolateMcg float32 `json:"folate_mcg"`

	// IodineMcg Iodine in micrograms
	IodineMcg float32 `json:"iodine_mcg"`

	// IronMg Iron in milligrams
	IronMg float32 `json:"iron_mg"`

	// MagnesiumMg Magnesium in milligrams
	MagnesiumMg float32 `json:"magnesium_mg"`

	// ManganeseMg Manganese in milligrams
	ManganeseMg float32 `json:"manganese_mg"`

	// MolybdenumMcg Molybdenum in micrograms
	MolybdenumMcg float32 `json:"molybdenum_mcg"`

	// MonounsaturatedFatG Monounsaturated fat in grams
	MonounsaturatedFatG float32 `json:"monounsaturated_fat_g"`

	// NiacinMg Niacin (B3) in milligrams
	NiacinMg float32 `json:"niacin_mg"`

	// Omega3AlaG Omega-3 ALA (Alpha-linolenic acid) in grams
	Omega3AlaG float32 `json:"omega3_ala_g"`

	// Omega3DhaG Omega-3 DHA (Docosahexaenoic acid) in grams
	Omega3DhaG float32 `json:"omega3_dha_g"`

	// Omega3EpaG Omega-3 EPA (Eicosapentaenoic acid) in grams
	Omega3EpaG float32 `json:"omega3_epa_g"`

	// Omega6G Omega-6 fatty acids in grams
	Omega6G float32 `json:"omega6_g"`

	// PantothenicAcidMg Pantothenic Acid (B5) in milligrams
	PantothenicAcidMg float32 `json:"pantothenic_acid_mg"`

	// PhosphorusMg Phosphorus in milligrams
	PhosphorusMg float32 `json:"phosphorus_mg"`

	// PolyunsaturatedFatG Polyunsaturated fat in grams
	PolyunsaturatedFatG float32 `json:"polyunsaturated_fat_g"`

	// PotassiumMg Potassium in milligrams
	PotassiumMg float32 `json:"potassium_mg"`

	// ProteinG Protein in grams
	ProteinG float32 `json:"protein_g"`

	// RiboflavinMg Riboflavin (B2) in milligrams
	RiboflavinMg float32 `json:"riboflavin_mg"`

	// SaturatedFatG Saturated fat in grams
	SaturatedFatG float32 `json:"saturated_fat_g"`

	// SeleniumMcg Selenium in micrograms
	SeleniumMcg float32 `json:"selenium_mcg"`

	// SodiumMg Sodium in milligrams
	SodiumMg float32 `json:"sodium_mg"`

	// ThiamineMg Thiamine (B1) in milligrams
	ThiamineMg float32 `json:"thiamine_mg"`

	// TotalCarbsG Total carbohydrates in grams
	TotalCarbsG float32 `json:"total_carbs_g"`

	// TotalFatG Total fat in grams
	TotalFatG float32 `json:"total_fat_g"`

	// TotalSugarsG Total sugars in grams
	TotalSugarsG float32 `json:"total_sugars_g"`

	// TransFatG Trans fat in grams
	TransFatG float32 `json:"trans_fat_g"`

	// VitaminAMcg Vitamin A in micrograms
	VitaminAMcg float32 `json:"vitamin_a_mcg"`

	// VitaminB12Mcg Vitamin B12 in micrograms
	VitaminB12Mcg float32 `json:"vitamin_b12_mcg"`

	// VitaminB6Mg Vitamin B6 in milligrams
	VitaminB6Mg float32 `json:"vitamin_b6_mg"`

	// VitaminCMg Vitamin C in milligrams
	VitaminCMg float32 `json:"vitamin_c_mg"`

	// VitaminDMcg Vitamin D in micrograms
	VitaminDMcg float32 `json:"vitamin_d_mcg"`

	// VitaminEMg Vitamin E in milligrams
	VitaminEMg float32 `json:"vitamin_e_mg"`

	// VitaminKMcg Vitamin K in micrograms
	VitaminKMcg float32 `json:"vitamin_k_mcg"`

	// ZincMg Zinc in milligrams
	ZincMg float32 `json:"zinc_mg"`
}

// Consumption defines model for Consumption.
type Consumption struct {
	// CreatedAt Timestamp when consumption was logged
	CreatedAt time.Time `json:"created_at"`

	// Id Consumption ID
	Id    string              `json:"id"`
	Items []ItemWithNutrition `json:"items"`

	// Labels Labels assigned to this consumption
	Labels *[]Label `json:"labels,omitempty"`

	// Note Additional note about the consumption
	Note    *string `json:"note"`
	Summary Summary `json:"summary"`

	// Title Custom title for the consumption
	Title *string `json:"title"`

	// Transcript Original transcribed text
	Transcript string `json:"transcript"`

	// UserId User ID who logged this consumption
	UserId string `json:"user_id"`
}

// ConsumptionsResponse defines model for ConsumptionsResponse.
type ConsumptionsResponse struct {
	Consumptions []Consumption `json:"consumptions"`

	// Count Number of consumptions returned
	Count int  `json:"count"`
	User  User `json:"user"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// ExpiresAt Optional expiration date (null for no expiration)
	ExpiresAt *time.Time `json:"expires_at"`

	// Name User-defined name for the API key
	Name string `json:"name"`

	// Scope Permissions scope - 'read' for GET requests only, 'read_write' for all operations
	Scope CreateAPIKeyRequestScope `json:"scope"`
}

// CreateAPIKeyRequestScope Permissions scope - 'read' for GET requests only, 'read_write' for all operations
type CreateAPIKeyRequestScope string

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	ApiKey APIKey `json:"api_key"`

	// Secret Full API key secret (only returned once at creation or rotation)
	Secret string `json:"secret"`
}

// DataPoint defines model for DataPoint.
type DataPoint struct {
	// Date Date for this data point
	Date time.Time `json:"date"`

	// Value Nutrient value for this date
	Value float32 `json:"value"`
}

// DeleteResponse defines model for DeleteResponse.
type DeleteResponse struct {
	// Id ID of the deleted consumption
	Id string `json:"id"`

	// Message Confirmation message
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Error Error message
	Error string `json:"error"`

	// Stack Stack trace (only in debug mode)
	Stack *[]string `json:"stack,omitempty"`

	// Timestamp Timestamp when the error occurred
	Timestamp time.Time `json:"timestamp"`

	// TraceId Request trace ID
	TraceId *string `json:"trace_id,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// Color Optional hex color for visual distinction
	Color *string `json:"color"`

	// CreatedAt When the event was created
	CreatedAt time.Time `json:"created_at"`

	// EndedAt When the event ended (optional)
	EndedAt *time.Time `json:"ended_at"`

	// EventTypeId Optional event type ID reference
	EventTypeId *string `json:"event_type_id"`

	// Id Event ID
	Id string `json:"id"`

	// Level Event intensity/severity/performance level (0-10)
	Level *int `json:"level"`

	// Name Event name
	Name string `json:"name"`

	// Note Optional notes about the event
	Note *string `json:"note"`

	// StartedAt When the event started
	StartedAt time.Time `json:"started_at"`

	// UpdatedAt When the event was last updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId User ID who owns this event
	UserId string `json:"user_id"`
}

// EventCreateRequest defines model for EventCreateRequest.
type EventCreateRequest struct {
	// Color Optional hex color for visual distinction
	Color *string `json:"color,omitempty"`

	// DurationMinutes Alternative to ended_at - duration in minutes from started_at
	DurationMinutes *int `json:"duration_minutes,omitempty"`

	// EndedAt When the event ended (optional)
	EndedAt *time.Time `json:"ended_at,omitempty"`

	// EventTypeId Optional event type ID reference
	EventTypeId *string `json:"event_type_id,omitempty"`

	// Level Event intensity/severity/performance level (0-10)
	Level *int `json:"level,omitempty"`

	// Name Event name
	Name string `json:"name"`

	// Note Optional notes about the event
	Note *string `json:"note,omitempty"`

	// StartedAt When the event started
	StartedAt time.Time `json:"started_at"`
}

// EventLink defines model for EventLink.
type EventLink struct {
	// ConsumptionId Consumption ID (if linked to a consumption)
	ConsumptionId *string `json:"consumption_id"`

	// ConsumptionItemId Consumption item ID (if linked to a consumption item)
	ConsumptionItemId *string `json:"consumption_item_id"`

	// CreatedAt When the link was created
	CreatedAt time.Time `json:"created_at"`

	// EventId Event ID
	EventId string `json:"event_id"`

	// Id Link ID
	Id string `json:"id"`
}

// EventLinkCreateRequest defines model for EventLinkCreateRequest.
type EventLinkCreateRequest struct {
	// ConsumptionId Consumption ID to link to (mutually exclusive with consumption_item_id)
	ConsumptionId *string `json:"consumption_id,omitempty"`

	// ConsumptionItemId Consumption item ID to link to (mutually exclusive with consumption_id)
	ConsumptionItemId *string `json:"consumption_item_id,omitempty"`
}

// EventType defines model for EventType.
type EventType struct {
	// Color Hex color for visual distinction (#RRGGBB)
	Color string `json:"color"`

	// CreatedAt When the event type was created
	CreatedAt time.Time `json:"created_at"`

	// DefaultName Default name suggestion when creating events of this type
	DefaultName *string `json:"default_name"`

	// Description Optional description of the event type
	Description *string `json:"description"`

	// Id Event type ID
	Id string `json:"id"`

	// Name Event type name
	Name string `json:"name"`

	// UpdatedAt When the event type was last updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId User ID who owns this event type
	UserId string `json:"user_id"`
}

// EventTypeCreateRequest defines model for EventTypeCreateRequest.
type EventTypeCreateRequest struct {
	// Color Hex color for visual distinction (#RRGGBB)
	Color string `json:"color"`

	// DefaultName Default name suggestion when creating events of this type
	DefaultName *string `json:"default_name,omitempty"`

	// Description Optional description of the event type
	Description *string `json:"description,omitempty"`

	// Name Event type name (unique per user, case-insensitive)
	Name string `json:"name"`
}

// EventTypeUpdateRequest defines model for EventTypeUpdateRequest.
type EventTypeUpdateRequest struct {
	// Color Hex color for visual distinction (#RRGGBB)
	Color *string `json:"color"`

	// DefaultName Default name suggestion when creating events of this type
	DefaultName *string `json:"default_name"`

	// Description Optional description of the event type
	Description *string `json:"description"`

	// Name Event type name (unique per user, case-insensitive)
	Name *string `json:"name,omitempty"`
}

// EventTypeWithUsage defines model for EventTypeWithUsage.
type EventTypeWithUsage struct {
	// Color Hex color for visual distinction (#RRGGBB)
	Color string `json:"color"`

	// CreatedAt When the event type was created
	CreatedAt time.Time `json:"created_at"`

	// DefaultName Default name suggestion when creating events of this type
	DefaultName *string `json:"default_name"`

	// Description Optional description of the event type
	Description *string `json:"description"`

	// EventCount Number of events using this event type
	EventCount int `json:"event_count"`

	// Id Event type ID
	Id string `json:"id"`

	// Name Event type name
	Name string `json:"name"`

	// UpdatedAt When the event type was last updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId User ID who owns this event type
	UserId string `json:"user_id"`
}

// EventTypesResponse defines model for EventTypesResponse.
type EventTypesResponse struct {
	EventTypes []EventTypeWithUsage `json:"event_types"`
}

// EventUpdateRequest defines model for EventUpdateRequest.
type EventUpdateRequest struct {
	// Color Optional hex color for visual distinction
	Color *string `json:"color"`

	// EndedAt When the event ended
	EndedAt *time.Time `json:"ended_at"`

	// EventTypeId Optional event type ID reference
	EventTypeId *string `json:"event_type_id"`

	// Level Event intensity/severity/performance level (0-10)
	Level *int `json:"level"`

	// Name Event name
	Name *string `json:"name,omitempty"`

	// Note Optional notes about the event
	Note *string `json:"note"`

	// StartedAt When the event started
	StartedAt *time.Time `json:"started_at,omitempty"`
}

// EventWithDetails defines model for EventWithDetails.
type EventWithDetails struct {
	// Color Optional hex color for visual distinction
	Color *string `json:"color"`

	// CreatedAt When the event was created
	CreatedAt time.Time `json:"created_at"`

	// EndedAt When the event ended
	EndedAt *time.Time `json:"ended_at"`

	// EventTypeId Reference to the event type
	EventTypeId *string `json:"event_type_id"`

	// Id Event ID
	Id string `json:"id"`

	// Labels Labels assigned to this event
	Labels []Label `json:"labels"`

	// Level Event intensity/severity/performance level (0-10)
	Level *int `json:"level"`

	// Links Consumption/item links for this event
	Links []EventLink `json:"links"`

	// Name Event name
	Name string `json:"name"`

	// Note Optional notes about the event
	Note *string `json:"note"`

	// StartedAt When the event started
	StartedAt time.Time `json:"started_at"`

	// UpdatedAt When the event was last updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId User ID who owns this event
	UserId string `json:"user_id"`
}

// EventsResponse defines model for EventsResponse.
type EventsResponse struct {
	Events []Event `json:"events"`
}

// ExportResponse defines model for ExportResponse.
type ExportResponse struct {
	DateRange struct {
		End   *time.Time `json:"end,omitempty"`
		Start *time.Time `json:"start,omitempty"`
	} `json:"date_range"`

	// Format Export format used
	Format ExportResponseFormat `json:"format"`

	// Series Time series data for each requested metric
	Series map[string][]DataPoint `json:"series"`
	User   User                   `json:"user"`
}

// ExportResponseFormat Export format used
type ExportResponseFormat string

// Favorite defines model for Favorite.
type Favorite struct {
	// ConsumptionId Consumption ID that was favorited
	ConsumptionId string `json:"consumption_id"`

	// CreatedAt When the favorite was created
	CreatedAt time.Time `json:"created_at"`

	// Id Favorite ID
	Id string `json:"id"`

	// UserId User ID who created the favorite
	UserId string `json:"user_id"`
}

// FavoriteWithConsumption defines model for FavoriteWithConsumption.
type FavoriteWithConsumption struct {
	Consumption Consumption `json:"consumption"`

	// ConsumptionId Consumption ID that was favorited
	ConsumptionId string `json:"consumption_id"`

	// CreatedAt When the favorite was created
	CreatedAt time.Time `json:"created_at"`

	// Id Favorite ID
	Id string `json:"id"`

	// UserId User ID who created the favorite
	UserId string `json:"user_id"`
}

// FavoritesResponse defines model for FavoritesResponse.
type FavoritesResponse struct {
	Favorites []FavoriteWithConsumption `json:"favorites"`
}

// GoalSetSummary defines model for GoalSetSummary.
type GoalSetSummary struct {
	// Category Category of the goal set
	Category GoalSetSummaryCategory `json:"category"`

	// CreatedAt When the goal set was created
	CreatedAt time.Time `json:"created_at"`

	// Name Name of the goal set
	Name string `json:"name"`

	// UpdatedAt When the goal set was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// GoalSetSummaryCategory Category of the goal set
type GoalSetSummaryCategory string

// GoalSetsResponse defines model for GoalSetsResponse.
type GoalSetsResponse struct {
	// ActiveGoalName Name of the currently active goal set
	ActiveGoalName string `json:"active_goal_name"`

	// GoalSets List of all available goal sets
	GoalSets []GoalSetSummary `json:"goal_sets"`
	User     User             `json:"user"`
}

// Goals defines model for Goals.
type Goals struct {
	// CustomName Name of the custom goal set (only present when source is "custom")
	CustomName *string   `json:"custom_name,omitempty"`
	LifeStage  LifeStage `json:"life_stage"`

	// Source Source of the goals (DRI defaults or custom overrides)
	Source GoalsSource `json:"source"`

	// Targets Target amounts for each nutrient
	Targets map[string]float32 `json:"targets"`

	// Units Units for each nutrient
	Units map[string]string `json:"units"`

	// UpperLimits Upper limit amounts for each nutrient (where defined)
	UpperLimits map[string]float32 `json:"upper_limits"`
}

// GoalsSource Source of the goals (DRI defaults or custom overrides)
type GoalsSource string

// GoalsResponse defines model for GoalsResponse.
type GoalsResponse struct {
	Goals Goals `json:"goals"`
	User  User  `json:"user"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// Item defines model for Item.
type Item struct {
	// Brand Brand name
	Brand *string `json:"brand"`

	// Grams Weight in grams (standardized internally)
	Grams float32 `json:"grams"`

	// Ingredients Ingredient list from Open Food Facts
	Ingredients *[]OFFIngredient `json:"ingredients,omitempty"`

	// Labels Labels assigned to this item
	Labels *[]Label `json:"labels,omitempty"`

	// Name Name of the food item
	Name string `json:"name"`

	// Note Additional note about the item
	Note      *string           `json:"note"`
	Nutrients *CompleteNutrient `json:"nutrients,omitempty"`

	// Url Link to the product URL (if available)
	Url *string `json:"url"`

	// UserQuantity Original user input quantity for display
	UserQuantity *float32 `json:"user_quantity"`

	// UserUnit Original user input unit for display
	UserUnit *string `json:"user_unit"`
}

// ItemWithNutrition defines model for ItemWithNutrition.
type ItemWithNutrition struct {
	Item Item `json:"item"`

	// Note Additional note (e.g., if nutrition data unavailable)
	Note *string `json:"note,omitempty"`
}

// Label defines model for Label.
type Label struct {
	// Color Hex color (#RRGGBB or RRGGBB)
	Color string `json:"color"`

	// CreatedAt When the label was created
	CreatedAt time.Time `json:"created_at"`

	// Description Optional description of the label
	Description *string `json:"description"`

	// Id Label ID
	Id string `json:"id"`

	// Name Label name
	Name string `json:"name"`

	// UpdatedAt When the label was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// LabelCreateRequest defines model for LabelCreateRequest.
type LabelCreateRequest struct {
	// Color Hex color (#RRGGBB or RRGGBB)
	Color string `json:"color"`

	// Description Optional description of the label
	Description *string `json:"description,omitempty"`

	// Name Label name (unique per user, case-insensitive)
	Name string `json:"name"`
}

// LabelUpdateRequest defines model for LabelUpdateRequest.
type LabelUpdateRequest struct {
	// Color Hex color (#RRGGBB or RRGGBB)
	Color *string `json:"color,omitempty"`

	// Description Optional description of the label
	Description *string `json:"description"`

	// Name Label name (unique per user, case-insensitive)
	Name *string `json:"name,omitempty"`
}

// LabelWithUsage defines model for LabelWithUsage.
type LabelWithUsage struct {
	// Color Hex color (#RRGGBB)
	Color string `json:"color"`

	// ConsumptionCount Number of consumptions using this label
	ConsumptionCount int `json:"consumption_count"`

	// CreatedAt When the label was created
	CreatedAt time.Time `json:"created_at"`

	// Description Optional description of the label
	Description *string `json:"description"`

	// Id Label ID
	Id string `json:"id"`

	// ItemCount Number of consumption items using this label
	ItemCount int `json:"item_count"`

	// Name Label name
	Name string `json:"name"`

	// UpdatedAt When the label was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// LabelsResponse defines model for LabelsResponse.
type LabelsResponse struct {
	Labels []LabelWithUsage `json:"labels"`
}

// LifeStage defines model for LifeStage.
type LifeStage struct {
	// AgeBracket Age bracket used for DRI lookup
	AgeBracket string `json:"age_bracket"`

	// Sex User sex for DRI calculation
	Sex LifeStageSex `json:"sex"`
}

// LifeStageSex User sex for DRI calculation
type LifeStageSex string

// OFFIngredient defines model for OFFIngredient.
type OFFIngredient struct {
	// Id Ingredient ID from Open Food Facts (e.g., "en:filtered-water")
	Id *string `json:"id,omitempty"`

	// PercentEstimate Estimated percentage of this ingredient in the product
	PercentEstimate *float32 `json:"percent_estimate"`

	// PercentMax Maximum possible percentage of this ingredient
	PercentMax *float32 `json:"percent_max"`

	// PercentMin Minimum possible percentage of this ingredient
	PercentMin *float32 `json:"percent_min"`

	// Text Display name of the ingredient (e.g., "Purified water")
	Text *string `json:"text,omitempty"`
}

// SetActiveGoalRequest defines model for SetActiveGoalRequest.
type SetActiveGoalRequest struct {
	// Name Name of the goal set to make active
	Name string `json:"name"`
}

// Summary defines model for Summary.
type Summary struct {
	// DailyValues Daily value amounts used for calculations
	DailyValues map[string]float32 `json:"daily_values"`

	// PercentOfDaily Percentage of daily values for each nutrient
	PercentOfDaily map[string]int   `json:"percent_of_daily"`
	Totals         CompleteNutrient `json:"totals"`
}

// UpdateBiometricsRequest defines model for UpdateBiometricsRequest.
type UpdateBiometricsRequest struct {
	// ActivityLevel Physical activity level
	ActivityLevel *UpdateBiometricsRequestActivityLevel `json:"activity_level,omitempty"`

	// BirthDate Date of birth
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// HeightCm Height in centimeters
	HeightCm *float32 `json:"height_cm,omitempty"`

	// Sex Biological sex for DRI calculations
	Sex *UpdateBiometricsRequestSex `json:"sex,omitempty"`

	// WeightKg Weight in kilograms
	WeightKg *float32 `json:"weight_kg,omitempty"`
}

// UpdateBiometricsRequestActivityLevel Physical activity level
type UpdateBiometricsRequestActivityLevel string

// UpdateBiometricsRequestSex Biological sex for DRI calculations
type UpdateBiometricsRequestSex string

// UpdateConsumptionRequest defines model for UpdateConsumptionRequest.
type UpdateConsumptionRequest struct {
	// ConsumedAt Timestamp when the consumption occurred (optional, defaults to current created_at)
	ConsumedAt *time.Time `json:"consumed_at"`

	// Items Updated items with nutrition information
	Items []ItemWithNutrition `json:"items"`

	// Note Additional note about the consumption
	Note *string `json:"note"`

	// Title Custom title for the consumption
	Title *string `json:"title"`
}

// UpdateGoalsRequest defines model for UpdateGoalsRequest.
type UpdateGoalsRequest struct {
	// Category Category of the goal set
	Category *UpdateGoalsRequestCategory `json:"category,omitempty"`

	// Name Custom name for the goal set (required for managing multiple goal sets)
	Name string `json:"name"`

	// Overrides Legacy field for nutrition goal overrides (use targets instead)
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Overrides *map[string]float32 `json:"overrides,omitempty"`

	// Targets Custom nutrition target overrides (minimum amounts to consume daily)
	Targets *map[string]float32 `json:"targets,omitempty"`

	// UpperLimits Custom nutrition upper limit overrides (maximum amounts to consume daily)
	UpperLimits *map[string]float32 `json:"upper_limits,omitempty"`
}

// UpdateGoalsRequestCategory Category of the goal set
type UpdateGoalsRequestCategory string

// User defines model for User.
type User struct {
	// AvatarUrl User avatar/profile image URL
	AvatarUrl *string `json:"avatar_url"`

	// CreatedAt User creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Email User email address
	Email string `json:"email"`

	// FullName User's full display name
	FullName *string `json:"full_name"`

	// Handle Unique user handle/username
	Handle string `json:"handle"`

	// Id User ID (auth.users.id UUID for Supabase)
	Id string `json:"id"`

	// SubscriptionTier User subscription level
	SubscriptionTier UserSubscriptionTier `json:"subscription_tier"`
}

// UserSubscriptionTier User subscription level
type UserSubscriptionTier string

// UserBiometrics defines model for UserBiometrics.
type UserBiometrics struct {
	// ActivityLevel Physical activity level
	ActivityLevel *UserBiometricsActivityLevel `json:"activity_level,omitempty"`

	// BirthDate Date of birth
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// HeightCm Height in centimeters
	HeightCm *float32 `json:"height_cm,omitempty"`

	// Sex Biological sex for DRI calculations
	Sex *UserBiometricsSex `json:"sex,omitempty"`

	// WeightKg Weight in kilograms
	WeightKg *float32 `json:"weight_kg,omitempty"`
}

// UserBiometricsActivityLevel Physical activity level
type UserBiometricsActivityLevel string

// UserBiometricsSex Biological sex for DRI calculations
type UserBiometricsSex string

// CreateConsumptionJSONBody defines parameters for CreateConsumption.
type CreateConsumptionJSONBody struct {
	union json.RawMessage
}

// CreateConsumptionMultipartBody defines parameters for CreateConsumption.
type CreateConsumptionMultipartBody struct {
	// Audio Audio file (webm, opus, mp3, wav) - ignored if text field is also provided
	Audio *openapi_types.File `json:"audio,omitempty"`

	// Text Text description of consumption - takes precedence over audio if both provided
	Text  *string `json:"text,omitempty"`
	union json.RawMessage
}

// CreateConsumptionJSONBody0 defines parameters for CreateConsumption.
type CreateConsumptionJSONBody0 struct {
	// Text Text description of consumption for AI processing
	Text string `json:"text"`
}

// CreateConsumptionJSONBody1 defines parameters for CreateConsumption.
type CreateConsumptionJSONBody1 struct {
	// ConsumptionId ID of an existing consumption to duplicate (skips AI processing, copies all items, nutrition data, title, note, and labels)
	ConsumptionId string `json:"consumption_id"`
}

// CreateConsumptionMultipartBody0 defines parameters for CreateConsumption.
type CreateConsumptionMultipartBody0 = interface{}

// CreateConsumptionMultipartBody1 defines parameters for CreateConsumption.
type CreateConsumptionMultipartBody1 = interface{}

// GetConsumptionsParams defines parameters for GetConsumptions.
type GetConsumptionsParams struct {
	// Limit Maximum number of consumptions to return (default 50, max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of consumptions to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Labels Comma-separated list of label names to filter by
	Labels *string `form:"labels,omitempty" json:"labels,omitempty"`

	// Match Label matching strategy - 'any' matches consumptions with at least one of the labels, 'all' matches consumptions with all labels
	Match *GetConsumptionsParamsMatch `form:"match,omitempty" json:"match,omitempty"`

	// Start Start date (RFC3339 format) - cannot be used together with 'days' parameter
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End End date (RFC3339 format) - cannot be used together with 'days' parameter
	End *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Days Number of days to look back from today - cannot be used together with 'start/end' parameters. Free tier limited to 7 days, Pro tier to 365 days.
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// GetConsumptionsParamsMatch defines parameters for GetConsumptions.
type GetConsumptionsParamsMatch string

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// Limit Maximum number of events to return (default 50, max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of events to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// StartDate Filter events starting from this date (ISO 8601)
	StartDate *time.Time `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Filter events ending before this date (ISO 8601)
	EndDate *time.Time `form:"end_date,omitempty" json:"end_date,omitempty"`

	// EventTypeId Filter by event type ID
	EventTypeId *string `form:"event_type_id,omitempty" json:"event_type_id,omitempty"`

	// LevelMin Filter events with level >= this value
	LevelMin *int `form:"level_min,omitempty" json:"level_min,omitempty"`

	// LevelMax Filter events with level <= this value
	LevelMax *int `form:"level_max,omitempty" json:"level_max,omitempty"`

	// Labels Comma-separated list of label names to filter by
	Labels *string `form:"labels,omitempty" json:"labels,omitempty"`

	// Match Label matching strategy - 'any' matches events with at least one of the labels, 'all' matches events with all labels
	Match *GetEventsParamsMatch `form:"match,omitempty" json:"match,omitempty"`
}

// GetEventsParamsMatch defines parameters for GetEvents.
type GetEventsParamsMatch string

// ExportDataParams defines parameters for ExportData.
type ExportDataParams struct {
	// Format Export format
	Format ExportDataParamsFormat `form:"format" json:"format"`

	// Start Start date (RFC3339 format)
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End End date (RFC3339 format)
	End *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Metrics Comma-separated list of metrics to include (defaults to common macros)
	Metrics *string `form:"metrics,omitempty" json:"metrics,omitempty"`
}

// ExportDataParamsFormat defines parameters for ExportData.
type ExportDataParamsFormat string

// GetGoalsParams defines parameters for GetGoals.
type GetGoalsParams struct {
	// GoalName Name of the specific goal set to retrieve. If not provided, returns the active goal set.
	GoalName *string `form:"goal_name,omitempty" json:"goal_name,omitempty"`

	// Source Force goal source. 'auto' uses user's active goal set if available, otherwise DRI. 'dri' forces DRI-only targets, ignoring custom overrides.
	Source *GetGoalsParamsSource `form:"source,omitempty" json:"source,omitempty"`
}

// GetGoalsParamsSource defines parameters for GetGoals.
type GetGoalsParamsSource string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// UpdateUserBiometricsJSONRequestBody defines body for UpdateUserBiometrics for application/json ContentType.
type UpdateUserBiometricsJSONRequestBody = UpdateBiometricsRequest

// CreateConsumptionJSONRequestBody defines body for CreateConsumption for application/json ContentType.
type CreateConsumptionJSONRequestBody CreateConsumptionJSONBody

// CreateConsumptionMultipartRequestBody defines body for CreateConsumption for multipart/form-data ContentType.
type CreateConsumptionMultipartRequestBody CreateConsumptionMultipartBody

// AssignConsumptionItemLabelsJSONRequestBody defines body for AssignConsumptionItemLabels for application/json ContentType.
type AssignConsumptionItemLabelsJSONRequestBody = AssignLabelsRequest

// UpdateConsumptionJSONRequestBody defines body for UpdateConsumption for application/json ContentType.
type UpdateConsumptionJSONRequestBody = UpdateConsumptionRequest

// AssignConsumptionLabelsJSONRequestBody defines body for AssignConsumptionLabels for application/json ContentType.
type AssignConsumptionLabelsJSONRequestBody = AssignLabelsRequest

// CreateEventTypeJSONRequestBody defines body for CreateEventType for application/json ContentType.
type CreateEventTypeJSONRequestBody = EventTypeCreateRequest

// UpdateEventTypeJSONRequestBody defines body for UpdateEventType for application/json ContentType.
type UpdateEventTypeJSONRequestBody = EventTypeUpdateRequest

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventCreateRequest

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = EventUpdateRequest

// AssignEventLabelsJSONRequestBody defines body for AssignEventLabels for application/json ContentType.
type AssignEventLabelsJSONRequestBody = AssignLabelsRequest

// CreateEventLinkJSONRequestBody defines body for CreateEventLink for application/json ContentType.
type CreateEventLinkJSONRequestBody = EventLinkCreateRequest

// AddToFavoritesJSONRequestBody defines body for AddToFavorites for application/json ContentType.
type AddToFavoritesJSONRequestBody = AddFavoriteRequest

// UpdateGoalsJSONRequestBody defines body for UpdateGoals for application/json ContentType.
type UpdateGoalsJSONRequestBody = UpdateGoalsRequest

// SetActiveGoalSetJSONRequestBody defines body for SetActiveGoalSet for application/json ContentType.
type SetActiveGoalSetJSONRequestBody = SetActiveGoalRequest

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = LabelCreateRequest

// UpdateLabelJSONRequestBody defines body for UpdateLabel for application/json ContentType.
type UpdateLabelJSONRequestBody = LabelUpdateRequest
