#!/usr/bin/env bash

set -euo pipefail

source script/env "$@"

count=3

# Run tests for all packages except supabase/tests (which contains integration tests)
go test -mod=vendor -race -count $count -v -cover -coverprofile=coverage.out $(go list ./... | grep -v '/supabase/tests')
