<script lang="ts">
  // No need for onMount or fetching - we'll embed content directly
</script>

<svelte:head>
  <title>Privacy Policy - Noot</title>
  <meta name="description" content="Noot Privacy Policy - How we collect, use, and protect your information." />
</svelte:head>

<div class="min-h-screen bg-base-100">
  <!-- Navigation spacing -->
  <div class="h-16"></div>
  
  <div class="container mx-auto px-4 py-8 max-w-4xl">
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body p-6 lg:p-8">
        <div class="prose prose-sm lg:prose max-w-none">
          <h1>Privacy Policy</h1>
          
          <p><strong>Last Updated:</strong> August 31, 2024</p>
          <p><strong>Contact Information:</strong> <a href="mailto:support@nootapp.io">support@nootapp.io</a></p>

          <h2>Introduction</h2>
          <p>Welcome to Noot, an AI-powered nutrition tracking application. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our application and services. We are committed to protecting your privacy and being transparent about our data practices.</p>
          <p>By using Noot, you agree to the collection and use of information in accordance with this Privacy Policy.</p>

          <h2>Information We Collect</h2>
          
          <h3>Information You Provide Directly</h3>
          <ul>
            <li><strong>Account Information</strong>: Email address, name, and password when you create an account</li>
            <li><strong>Profile Information</strong>: Nutritional preferences, dietary restrictions, health goals, and other profile details you choose to provide</li>
            <li><strong>Audio Recordings</strong>: Voice recordings of your meal descriptions and food consumption data</li>
            <li><strong>Payment Information</strong>: Billing details processed securely through Stripe (we do not store complete credit card information)</li>
          </ul>

          <h3>Information We Collect Automatically</h3>
          <ul>
            <li><strong>Usage Data</strong>: How you interact with our application, including features used, pages visited, and time spent</li>
            <li><strong>Device Information</strong>: Device type, operating system, browser type, IP address, and device identifiers</li>
            <li><strong>Cookies and Similar Technologies</strong>: To enhance your experience and analyze usage patterns</li>
            <li><strong>Location Data</strong>: General location information (if permitted) to improve nutrition recommendations</li>
          </ul>

          <h3>Information Generated by Our Services</h3>
          <ul>
            <li><strong>Transcriptions</strong>: Text transcriptions of your audio recordings created using AI services</li>
            <li><strong>Nutrition Analysis</strong>: Parsed nutrition data, calorie counts, macro and micronutrient breakdowns</li>
            <li><strong>Analytics and Insights</strong>: Daily, weekly, and monthly nutrition summaries and trends</li>
            <li><strong>AI-Generated Content</strong>: Recommendations, insights, and suggestions based on your data</li>
          </ul>

          <h2>How We Use Your Information</h2>
          <p>We use your information to:</p>
          <ul>
            <li><strong>Provide Core Services</strong>: Process audio recordings, generate nutrition analysis, and provide tracking capabilities</li>
            <li><strong>Improve User Experience</strong>: Personalize recommendations, improve accuracy of nutrition parsing, and enhance app functionality</li>
            <li><strong>Account Management</strong>: Create and manage your account, process payments, and provide customer support</li>
            <li><strong>Communication</strong>: Send service-related notifications, updates, and respond to inquiries</li>
            <li><strong>Analytics</strong>: Understand usage patterns to improve our services and develop new features</li>
            <li><strong>Legal Compliance</strong>: Comply with applicable laws and protect our rights and interests</li>
          </ul>

          <h2>Legal Basis for Processing (GDPR)</h2>
          <p>For users in the European Union, our legal basis for processing your personal information includes:</p>
          <ul>
            <li><strong>Consent</strong>: When you explicitly consent to specific processing activities</li>
            <li><strong>Contract Performance</strong>: To provide the services you've requested</li>
            <li><strong>Legitimate Interests</strong>: To improve our services, prevent fraud, and ensure security</li>
            <li><strong>Legal Compliance</strong>: To meet applicable legal requirements</li>
          </ul>

          <h2>Information Sharing and Disclosure</h2>
          <p><strong>We do not sell your personal information to third parties.</strong> We may share your information in the following circumstances:</p>
          
          <h3>Service Providers and Third Parties</h3>
          <ul>
            <li><strong>Stripe</strong>: Payment processing (governed by Stripe's privacy policy)</li>
            <li><strong>Supabase</strong>: Authentication and database services (governed by Supabase's privacy policy)</li>
            <li><strong>Cloudflare</strong>: Hosting and content delivery (governed by Cloudflare's privacy policy)</li>
            <li><strong>AI Service Providers</strong>: Audio transcription and natural language processing services</li>
            <li><strong>Analytics Providers</strong>: To understand usage patterns and improve our services</li>
          </ul>

          <h3>Legal Requirements</h3>
          <ul>
            <li><strong>Legal Compliance</strong>: When required by law, regulation, legal process, or governmental request</li>
            <li><strong>Safety and Security</strong>: To protect rights, property, or safety of Noot, our users, or others</li>
            <li><strong>Business Transfers</strong>: In connection with mergers, acquisitions, or sale of assets (with notice to users)</li>
          </ul>

          <h2>Your Rights and Choices</h2>
          <h3>Data Subject Rights (GDPR/CPRA)</h3>
          <p>You have the following rights regarding your personal information:</p>
          <ul>
            <li><strong>Access</strong>: Request access to your personal information</li>
            <li><strong>Rectification</strong>: Request correction of inaccurate or incomplete information</li>
            <li><strong>Erasure</strong>: Request deletion of your personal information</li>
            <li><strong>Portability</strong>: Request transfer of your data in a portable format</li>
            <li><strong>Restriction</strong>: Request restriction of processing in certain circumstances</li>
            <li><strong>Objection</strong>: Object to processing based on legitimate interests</li>
            <li><strong>Withdraw Consent</strong>: Withdraw consent for processing based on consent</li>
          </ul>

          <p>To exercise these rights, contact us at <a href="mailto:support@nootapp.io">support@nootapp.io</a>. We will respond within the timeframes required by applicable law.</p>

          <h2>Data Security</h2>
          <p>We implement appropriate technical and organizational measures to protect your information:</p>
          <ul>
            <li><strong>Encryption</strong>: Data encrypted in transit and at rest</li>
            <li><strong>Access Controls</strong>: Limited access to personal information on a need-to-know basis</li>
            <li><strong>Security Monitoring</strong>: Regular security assessments and monitoring for threats</li>
            <li><strong>Incident Response</strong>: Procedures for handling security incidents and data breaches</li>
          </ul>
          <p>However, no method of transmission or storage is 100% secure, and we cannot guarantee absolute security.</p>

          <h2>Health Information Disclaimer</h2>
          <div class="alert alert-warning">
            <p><strong>Important</strong>: Noot is designed for informational and tracking purposes only and is not intended to provide medical advice, diagnosis, or treatment. Our nutrition analysis and recommendations should not replace professional medical or nutritional advice.</p>
            <ul>
              <li><strong>Not HIPAA Covered</strong>: We are not a covered entity under HIPAA and do not provide healthcare services</li>
              <li><strong>Consult Professionals</strong>: Always consult healthcare professionals for medical or nutritional advice</li>
              <li><strong>Emergency Situations</strong>: Do not use Noot for medical emergencies</li>
            </ul>
          </div>

          <h2>Children's Privacy</h2>
          <p>Noot is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you believe we have collected information from a child under 13, please contact us immediately.</p>

          <h2>International Data Transfers</h2>
          <p>Your information may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place for international transfers.</p>
          <p><em>Note: We currently do not have representatives in the European Union or United Kingdom.</em></p>

          <h2>Changes to This Privacy Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify you of material changes by updating the "Last Updated" date and sending email notifications for significant changes.</p>

          <h2>Contact Information</h2>
          <p>If you have questions, concerns, or requests regarding this Privacy Policy, please contact us:</p>
          <p><strong>Email:</strong> <a href="mailto:support@nootapp.io">support@nootapp.io</a></p>
          <p><strong>Mailing Address:</strong><br>
          Noot Inc.<br>
          California, United States</p>
        </div>
        
        <div class="divider mt-8"></div>
        
        <div class="text-center">
          <a href="/" class="btn btn-primary">Back to Home</a>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  :global(.prose h1) {
    @apply text-3xl font-bold mb-4 text-primary;
  }
  
  :global(.prose h2) {
    @apply text-2xl font-semibold mb-3 mt-6 text-base-content;
  }
  
  :global(.prose h3) {
    @apply text-xl font-medium mb-2 mt-4 text-base-content;
  }
  
  :global(.prose p) {
    @apply mb-3 text-base-content/80;
  }
  
  :global(.prose strong) {
    @apply font-semibold text-base-content;
  }
  
  :global(.prose ul) {
    @apply list-disc ml-6 mb-4;
  }
  
  :global(.prose li) {
    @apply mb-1 text-base-content/80;
  }
  
  :global(.prose a) {
    @apply text-primary hover:underline;
  }
</style>