-- Migration 003: Create items table for reusable nutrition data with soft TTL (PostgreSQL)
CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    normalized_name TEXT NOT NULL,
    normalized_brand TEXT NOT NULL DEFAULT '',
    display_name TEXT NOT NULL,
    display_brand TEXT DEFAULT '',
    -- Nutrition data in canonical units (grams/mg/kcal)
    calories_per_100g REAL NOT NULL DEFAULT 0,
    protein_g_per_100g REAL NOT NULL DEFAULT 0,
    total_fat_g_per_100g REAL NOT NULL DEFAULT 0,
    saturated_fat_g_per_100g REAL NOT NULL DEFAULT 0,
    trans_fat_g_per_100g REAL NOT NULL DEFAULT 0,
    cholesterol_mg_per_100g REAL NOT NULL DEFAULT 0,
    sodium_mg_per_100g REAL NOT NULL DEFAULT 0,
    total_carbs_g_per_100g REAL NOT NULL DEFAULT 0,
    dietary_fiber_g_per_100g REAL NOT NULL DEFAULT 0,
    total_sugars_g_per_100g REAL NOT NULL DEFAULT 0,
    added_sugars_g_per_100g REAL NOT NULL DEFAULT 0,
    -- Additional nutrition fields
    vitamin_a_mcg_per_100g REAL NOT NULL DEFAULT 0,
    vitamin_c_mg_per_100g REAL NOT NULL DEFAULT 0,
    vitamin_d_mcg_per_100g REAL NOT NULL DEFAULT 0,
    vitamin_e_mg_per_100g REAL NOT NULL DEFAULT 0,
    vitamin_k_mcg_per_100g REAL NOT NULL DEFAULT 0,
    thiamine_mg_per_100g REAL NOT NULL DEFAULT 0,
    riboflavin_mg_per_100g REAL NOT NULL DEFAULT 0,
    niacin_mg_per_100g REAL NOT NULL DEFAULT 0,
    vitamin_b6_mg_per_100g REAL NOT NULL DEFAULT 0,
    folate_mcg_per_100g REAL NOT NULL DEFAULT 0,
    vitamin_b12_mcg_per_100g REAL NOT NULL DEFAULT 0,
    biotin_mcg_per_100g REAL NOT NULL DEFAULT 0,
    pantothenic_acid_mg_per_100g REAL NOT NULL DEFAULT 0,
    choline_mg_per_100g REAL NOT NULL DEFAULT 0,
    calcium_mg_per_100g REAL NOT NULL DEFAULT 0,
    iron_mg_per_100g REAL NOT NULL DEFAULT 0,
    magnesium_mg_per_100g REAL NOT NULL DEFAULT 0,
    phosphorus_mg_per_100g REAL NOT NULL DEFAULT 0,
    potassium_mg_per_100g REAL NOT NULL DEFAULT 0,
    zinc_mg_per_100g REAL NOT NULL DEFAULT 0,
    copper_mg_per_100g REAL NOT NULL DEFAULT 0,
    manganese_mg_per_100g REAL NOT NULL DEFAULT 0,
    selenium_mcg_per_100g REAL NOT NULL DEFAULT 0,
    iodine_mcg_per_100g REAL NOT NULL DEFAULT 0,
    molybdenum_mcg_per_100g REAL NOT NULL DEFAULT 0,
    chromium_mcg_per_100g REAL NOT NULL DEFAULT 0,
    fluoride_mg_per_100g REAL NOT NULL DEFAULT 0,
    chloride_mg_per_100g REAL NOT NULL DEFAULT 0,
    -- Original serving data for the exact item
    original_serving_grams REAL,
    original_calories REAL,
    original_protein_g REAL,
    original_total_fat_g REAL,
    original_saturated_fat_g REAL,
    original_trans_fat_g REAL,
    original_cholesterol_mg REAL,
    original_sodium_mg REAL,
    original_total_carbs_g REAL,
    original_dietary_fiber_g REAL,
    original_total_sugars_g REAL,
    original_added_sugars_g REAL,
    original_vitamin_a_mcg REAL,
    original_vitamin_c_mg REAL,
    original_vitamin_d_mcg REAL,
    original_vitamin_e_mg REAL,
    original_vitamin_k_mcg REAL,
    original_thiamine_mg REAL,
    original_riboflavin_mg REAL,
    original_niacin_mg REAL,
    original_vitamin_b6_mg REAL,
    original_folate_mcg REAL,
    original_vitamin_b12_mcg REAL,
    original_biotin_mcg REAL,
    original_pantothenic_acid_mg REAL,
    original_choline_mg REAL,
    original_calcium_mg REAL,
    original_iron_mg REAL,
    original_magnesium_mg REAL,
    original_phosphorus_mg REAL,
    original_potassium_mg REAL,
    original_zinc_mg REAL,
    original_copper_mg REAL,
    original_manganese_mg REAL,
    original_selenium_mcg REAL,
    original_iodine_mcg REAL,
    original_molybdenum_mcg REAL,
    original_chromium_mcg REAL,
    original_fluoride_mg REAL,
    original_chloride_mg REAL,
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(normalized_name, normalized_brand)
);

CREATE INDEX IF NOT EXISTS idx_items_normalized ON items(normalized_name, normalized_brand);
CREATE INDEX IF NOT EXISTS idx_items_display_name ON items(display_name);
